import { describe, it, expect } from "vitest";
import {
  ALLOWED_COLUMNS,
  CURRENCY_GBP_COLUMNS,
  DERIVED_GROUP_COLUMNS,
  derivedGroupColumns,
  isCurrencyField,
  gbpAlias,
  currencyKeyAlias,
  validatePivotConfig,
  buildPivotSQL,
  formatPivotResults,
  buildPivotData,
} from "./pivot-engine";
import type { PivotConfig, PivotValueConfig } from "./types";

// ─── ALLOWED_COLUMNS ────────────────────────────────────────────────────────

describe("ALLOWED_COLUMNS", () => {
  it("resolves known columns using un-aliased table names", () => {
    // We deliberately use full table names (not aliases like `sr`/`l`/`p`) so
    // the WHERE clause generated by shared Drizzle helpers — which emits
    // `"sales_records"."..."` — resolves against the pivot query FROM clause.
    expect(ALLOWED_COLUMNS.get("product_name")).toBe("products.name");
    // Phase 07-06 — pivot-engine's logical "outlet_code" dimension now
    // resolves to locations.customer_code (the canonical hotel-level
    // identifier). The locations.outlet_code column is gone (migration 0040).
    expect(ALLOWED_COLUMNS.get("outlet_code")).toBe("locations.customer_code");
    expect(ALLOWED_COLUMNS.get("hotel_name")).toBe("locations.name");
    expect(ALLOWED_COLUMNS.get("net_amount")).toBe(
      "sales_records.net_amount::numeric",
    );
    expect(ALLOWED_COLUMNS.get("booking_fee")).toContain("is_weknow_fee");
  });

  it("booking_fee predicate matches both 9991 and 9992 fee rows", () => {
    // Symmetry with buildIsFeeCondition() in queries/shared.ts: pivot's
    // booking_fee value/metric must include 9991 (Booking Fee) AND 9992
    // (Cash Handling Fee). Post-D10 both are flagged via is_weknow_fee=true
    // by the parser, so the predicate is a single column check.
    const expr = ALLOWED_COLUMNS.get("booking_fee")!;
    expect(expr).toContain("sales_records.is_weknow_fee = true");
  });

  it("booking_fee SUM aggregates over both 9991 and 9992 rows", () => {
    // End-to-end check: the SUM expression generated for the booking_fee
    // metric should include net_amount for any row matching the fee predicate
    // and 0 otherwise. is_weknow_fee=true covers both NetSuite codes 9991 and
    // 9992 by virtue of the parser's per-code assignment (D10).
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "booking_fee", aggregation: "sum" }],
    });
    expect(sql).toContain("SUM(COALESCE((CASE WHEN");
    expect(sql).toContain("sales_records.is_weknow_fee = true");
    expect(sql).toContain("THEN sales_records.net_amount::numeric ELSE 0 END)");
  });

  it("rejects unknown columns", () => {
    expect(ALLOWED_COLUMNS.get("unknown_field")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("category_name")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("__proto__")).toBeUndefined();
  });

  it("rejects columns that are not in the schema", () => {
    // gross_amount, quantity, sale_commission, discount_amount, region are
    // not on the current sales_records / locations schema. They must not
    // resolve, otherwise the pivot SQL will reference non-existent columns
    // and Postgres will 42703.
    expect(ALLOWED_COLUMNS.get("gross_amount")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("quantity")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("sale_commission")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("discount_amount")).toBeUndefined();
    expect(ALLOWED_COLUMNS.get("region")).toBeUndefined();
  });
});

describe("DERIVED_GROUP_COLUMNS", () => {
  it("resolves derived columns", () => {
    expect(DERIVED_GROUP_COLUMNS.get("sale_month")).toContain("TO_CHAR");
    expect(DERIVED_GROUP_COLUMNS.get("sale_year")).toContain("EXTRACT");
    expect(DERIVED_GROUP_COLUMNS.get("sale_hour")).toContain("transaction_time");
  });
});

// ─── derivedGroupColumns(displayTz) — D6 / Task 2.12 ────────────────────────
//
// `sale_hour` MUST be timezone-aware so the Pivot Table's hour-of-day grouping
// matches the Hourly Distribution widget. The same SQL pattern is used in
// both places: reconstruct (date + time) as a UTC timestamptz, then convert
// into the target zone with a second AT TIME ZONE.

describe("derivedGroupColumns (D6 timezone awareness)", () => {
  it("default ('local') buckets sale_hour by per-row locations.iana_timezone", () => {
    const map = derivedGroupColumns();
    const expr = map.get("sale_hour")!;
    expect(expr).toContain("EXTRACT(HOUR FROM");
    // (date + time) reconstruction landing in UTC timestamptz.
    expect(expr).toContain(
      "(sales_records.transaction_date + sales_records.transaction_time) AT TIME ZONE 'UTC'",
    );
    // Per-row zone — locations.iana_timezone resolves to each property's IANA zone.
    expect(expr).toContain("AT TIME ZONE locations.iana_timezone");
    expect(expr).toMatch(/::TEXT$/);
  });

  it("'utc' mode pins the second AT TIME ZONE to the UTC literal", () => {
    const map = derivedGroupColumns("utc");
    const expr = map.get("sale_hour")!;
    expect(expr).toContain("AT TIME ZONE 'UTC'"); // both sides use 'UTC'
    expect(expr).not.toContain("locations.iana_timezone");
  });

  it("sale_month / sale_year are unchanged across modes (date-only, no zone)", () => {
    const local = derivedGroupColumns("local");
    const utc = derivedGroupColumns("utc");
    expect(local.get("sale_month")).toBe(utc.get("sale_month"));
    expect(local.get("sale_year")).toBe(utc.get("sale_year"));
    expect(local.get("sale_month")).toContain("TO_CHAR");
    expect(local.get("sale_year")).toContain(
      "EXTRACT(YEAR FROM sales_records.transaction_date)",
    );
  });
});

describe("buildPivotSQL — sale_hour timezone wiring", () => {
  const config: PivotConfig = {
    rowFields: ["sale_hour"],
    columnFields: [],
    values: [{ field: "net_amount", aggregation: "sum" }],
  };

  it("emits per-row iana_timezone when displayTz is 'local' (default)", () => {
    const sql = buildPivotSQL(config);
    expect(sql).toContain("AT TIME ZONE locations.iana_timezone");
    // The SELECT also aliases by the logical name so the engine can map
    // back to the dimension at format time.
    expect(sql).toContain('AS "sale_hour"');
  });

  it("emits the constant 'UTC' both sides when displayTz is 'utc'", () => {
    const sql = buildPivotSQL(config, undefined, "utc");
    // The pivot SQL repeats the dimension expression in SELECT, GROUP BY and
    // ORDER BY (3×), and each occurrence carries both AT-TIME-ZONE steps —
    // so we expect at least 6 'UTC' literals in 'utc' mode and zero
    // references to per-row iana_timezone.
    expect((sql.match(/AT TIME ZONE 'UTC'/g) ?? []).length).toBeGreaterThanOrEqual(2);
    expect(sql).not.toContain("locations.iana_timezone");
  });

  it("keeps sale_month emission timezone-agnostic in either mode", () => {
    const cfg: PivotConfig = {
      rowFields: ["sale_month"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    };
    expect(buildPivotSQL(cfg, undefined, "local")).toContain("TO_CHAR");
    expect(buildPivotSQL(cfg, undefined, "utc")).toContain("TO_CHAR");
  });
});

// ─── validatePivotConfig ────────────────────────────────────────────────────

describe("validatePivotConfig", () => {
  const validConfig: PivotConfig = {
    rowFields: ["product_name"],
    columnFields: ["sale_month"],
    values: [{ field: "net_amount", aggregation: "sum" }],
  };

  it("accepts a valid config", () => {
    expect(validatePivotConfig(validConfig)).toEqual([]);
  });

  it("rejects missing values", () => {
    const errors = validatePivotConfig({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [],
    });
    expect(errors).toHaveLength(1);
    expect(errors[0].field).toBe("values");
    expect(errors[0].message).toContain("required");
  });

  it("rejects unknown row field", () => {
    const errors = validatePivotConfig({
      rowFields: ["bogus_field"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(errors.some((e) => e.message.includes("bogus_field"))).toBe(true);
  });

  it("rejects unknown column field", () => {
    const errors = validatePivotConfig({
      rowFields: [],
      columnFields: ["no_such_col"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(errors.some((e) => e.message.includes("no_such_col"))).toBe(true);
  });

  it("rejects unknown value field", () => {
    const errors = validatePivotConfig({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "bad_metric", aggregation: "sum" }],
    });
    expect(errors.some((e) => e.message.includes("bad_metric"))).toBe(true);
  });

  it("rejects invalid aggregation", () => {
    const errors = validatePivotConfig({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "median" as never }],
    });
    expect(errors.some((e) => e.message.includes("median"))).toBe(true);
  });

  it("rejects field in both rows and columns", () => {
    const errors = validatePivotConfig({
      rowFields: ["product_name"],
      columnFields: ["product_name"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(
      errors.some((e) => e.message.includes("both rows and columns")),
    ).toBe(true);
  });

  it("accepts derived fields (sale_month, sale_year, sale_hour)", () => {
    const errors = validatePivotConfig({
      rowFields: ["sale_month"],
      columnFields: ["sale_year"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(errors).toEqual([]);
  });

  it("rejects metric columns used as dimensions", () => {
    const errors = validatePivotConfig({
      rowFields: ["net_amount"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(errors.some((e) => e.field === "rowFields")).toBe(true);
  });
});

// ─── buildPivotSQL ──────────────────────────────────────────────────────────

describe("buildPivotSQL", () => {
  it("builds SQL with row + column + value", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: ["sale_month"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });

    expect(sql).toContain("SELECT");
    expect(sql).toContain('locations.name AS "hotel_name"');
    expect(sql).toContain(
      "SUM(COALESCE(sales_records.net_amount::numeric, 0))",
    );
    expect(sql).toContain(
      "INNER JOIN locations ON sales_records.location_id = locations.id",
    );
    expect(sql).toContain(
      "INNER JOIN products ON sales_records.product_id = products.id",
    );
    expect(sql).toContain("GROUP BY");
    expect(sql).toContain("LIMIT");
  });

  it("includes WHERE clause when provided", () => {
    const sql = buildPivotSQL(
      {
        rowFields: ["product_name"],
        columnFields: [],
        values: [{ field: "net_amount", aggregation: "count" }],
      },
      `"sales_records"."transaction_date" >= '2025-01-01'`,
    );
    expect(sql).toContain(
      `WHERE "sales_records"."transaction_date" >= '2025-01-01'`,
    );
  });

  it("uses COUNT scoped to non-fee, non-reversal rows for count aggregation (D1)", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "count" }],
    });
    // D1: "Transactions" count = real customer transactions only.
    expect(sql).toContain(
      "COUNT(sales_records.net_amount::numeric) FILTER (WHERE sales_records.is_weknow_fee = false AND sales_records.is_reversal = false)",
    );
  });

  it("handles derived column in group by", () => {
    const sql = buildPivotSQL({
      rowFields: ["sale_month"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "avg" }],
    });
    expect(sql).toContain(
      "TO_CHAR(sales_records.transaction_date, 'Mon YYYY')",
    );
  });
});

// ─── buildPivotData ─────────────────────────────────────────────────────────

describe("buildPivotData", () => {
  const values: PivotValueConfig[] = [
    { field: "net_amount", aggregation: "sum" },
  ];

  it("builds flat rows when no column fields", () => {
    const rawRows = [
      { hotel_name: "Hotel A", sum_net_amount: 1000 },
      { hotel_name: "Hotel B", sum_net_amount: 2000 },
    ];
    const result = buildPivotData(rawRows, ["hotel_name"], [], values);

    expect(result).toHaveLength(2);
    expect(result[0].dimensions.hotel_name).toBe("Hotel A");
    expect(result[0].cells["sum_net_amount"].value).toBe(1000);
    expect(result[1].dimensions.hotel_name).toBe("Hotel B");
  });

  it("builds crosstab when column fields present", () => {
    const rawRows = [
      { hotel_name: "Hotel A", sale_month: "Jan 2025", sum_net_amount: 500 },
      { hotel_name: "Hotel A", sale_month: "Feb 2025", sum_net_amount: 700 },
      { hotel_name: "Hotel B", sale_month: "Jan 2025", sum_net_amount: 300 },
    ];
    const result = buildPivotData(
      rawRows,
      ["hotel_name"],
      ["sale_month"],
      values,
    );

    expect(result).toHaveLength(2);

    const hotelA = result.find((r) => r.dimensions.hotel_name === "Hotel A")!;
    expect(hotelA.cells["Jan 2025"].value).toBe(500);
    expect(hotelA.cells["Feb 2025"].value).toBe(700);

    const hotelB = result.find((r) => r.dimensions.hotel_name === "Hotel B")!;
    expect(hotelB.cells["Jan 2025"].value).toBe(300);
    expect(hotelB.cells["Feb 2025"]).toBeUndefined();
  });

  it("handles empty rows", () => {
    const result = buildPivotData([], ["hotel_name"], [], values);
    expect(result).toEqual([]);
  });
});

// ─── formatPivotResults ─────────────────────────────────────────────────────

describe("formatPivotResults", () => {
  const config: PivotConfig = {
    rowFields: ["hotel_name"],
    columnFields: [],
    values: [{ field: "net_amount", aggregation: "sum" }],
  };

  it("formats flat results with headers and grand totals", () => {
    const rawRows = [
      { hotel_name: "Hotel A", sum_net_amount: 1000 },
      { hotel_name: "Hotel B", sum_net_amount: 2500 },
    ];
    const result = formatPivotResults(rawRows, config);

    expect(result.headers).toContain("Hotel");
    expect(result.headers).toContain("Sum of Revenue");
    expect(result.rows).toHaveLength(2);
    expect(result.rowCount).toBe(2);
    expect(result.truncated).toBe(false);
  });

  it("calculates sum grand total", () => {
    const rawRows = [
      { hotel_name: "A", sum_net_amount: 1000 },
      { hotel_name: "B", sum_net_amount: 3000 },
    ];
    const result = formatPivotResults(rawRows, config);
    expect(result.grandTotals["sum_net_amount"].value).toBe(4000);
  });

  it("calculates avg grand total", () => {
    const avgConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "avg" }],
    };
    const rawRows = [
      { hotel_name: "A", avg_net_amount: 100 },
      { hotel_name: "B", avg_net_amount: 200 },
    ];
    const result = formatPivotResults(rawRows, avgConfig);
    expect(result.grandTotals["avg_net_amount"].value).toBe(150);
  });

  it("calculates count grand total", () => {
    const countConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "count" }],
    };
    const rawRows = [
      { hotel_name: "A", count_net_amount: 10 },
      { hotel_name: "B", count_net_amount: 15 },
    ];
    const result = formatPivotResults(rawRows, countConfig);
    expect(result.grandTotals["count_net_amount"].value).toBe(25);
  });

  it("calculates min grand total", () => {
    const minConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "min" }],
    };
    const rawRows = [
      { hotel_name: "A", min_net_amount: 500 },
      { hotel_name: "B", min_net_amount: 200 },
    ];
    const result = formatPivotResults(rawRows, minConfig);
    expect(result.grandTotals["min_net_amount"].value).toBe(200);
  });

  it("calculates max grand total", () => {
    const maxConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "max" }],
    };
    const rawRows = [
      { hotel_name: "A", max_net_amount: 500 },
      { hotel_name: "B", max_net_amount: 800 },
    ];
    const result = formatPivotResults(rawRows, maxConfig);
    expect(result.grandTotals["max_net_amount"].value).toBe(800);
  });

  it("handles empty results", () => {
    const result = formatPivotResults([], config);
    expect(result.rows).toEqual([]);
    expect(result.rowCount).toBe(0);
    expect(result.truncated).toBe(false);
    expect(result.grandTotals["sum_net_amount"].value).toBe(0);
  });

  it("marks truncated when over limit", () => {
    // Build more than 10_000 rows
    const rawRows = Array.from({ length: 10_002 }, (_, i) => ({
      hotel_name: `Hotel ${i}`,
      sum_net_amount: i * 10,
    }));
    const result = formatPivotResults(rawRows, config);
    expect(result.truncated).toBe(true);
    expect(result.rows).toHaveLength(10_000);
  });

  // ─── Task 2.4 — AVG grand total uses weighted recombination ───────────────
  // Without this fix the engine averages per-row averages (Simpson's
  // paradox). buildPivotSQL projects __avg_sum_<field> + __avg_count_<field>
  // companions specifically so formatPivotResults can recompute
  // SUM(numerators) / SUM(denominators).
  it("avg grand total: weighted recombination from sum + count companions (Task 2.4)", () => {
    const avgConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "avg" }],
    };
    // Hotel A: avg basket £10 over 1000 transactions (sum=10000, count=1000).
    // Hotel B: avg basket £20 over 5 transactions    (sum=100,   count=5).
    // True weighted avg = 10100 / 1005 ≈ 10.0497 — NOT (10+20)/2 = 15.
    const rawRows = [
      {
        hotel_name: "A",
        avg_net_amount: 10,
        __avg_sum_net_amount: 10000,
        __avg_count_net_amount: 1000,
      },
      {
        hotel_name: "B",
        avg_net_amount: 20,
        __avg_sum_net_amount: 100,
        __avg_count_net_amount: 5,
      },
    ];
    const result = formatPivotResults(rawRows, avgConfig);
    expect(result.grandTotals["avg_net_amount"].value).toBeCloseTo(
      10100 / 1005,
      4,
    );
    // Sanity: explicitly NOT the broken mean-of-means.
    expect(result.grandTotals["avg_net_amount"].value).not.toBe(15);
  });

  it("avg grand total: falls back to mean-of-means when companions absent", () => {
    // Existing callers / tests that synthesize raw rows without companions
    // must not regress to NaN or zero.
    const avgConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "avg" }],
    };
    const rawRows = [
      { hotel_name: "A", avg_net_amount: 100 },
      { hotel_name: "B", avg_net_amount: 200 },
    ];
    const result = formatPivotResults(rawRows, avgConfig);
    expect(result.grandTotals["avg_net_amount"].value).toBe(150);
  });

  it("buildPivotSQL projects __avg_sum_/__avg_count_ companions for avg (Task 2.4)", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "avg" }],
    });
    expect(sql).toContain('AS "__avg_sum_net_amount"');
    expect(sql).toContain('AS "__avg_count_net_amount"');
    // Companions only emitted for avg, not for sum.
    const sumSql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(sumSql).not.toContain("__avg_sum_");
    expect(sumSql).not.toContain("__avg_count_");
  });

  // ─── Task 2.5 — Grand totals row populated under column-pivoting ──────────
  // Previously grandTotals was keyed by `${aggregation}_${field}` (e.g.
  // "sum_net_amount") while crosstab cells were keyed by colKey (e.g.
  // "Jan 2025"). The UI looks up grand totals by the same cellKey it uses
  // for headers, so every cell rendered as "—".
  it("grand totals are keyed by crosstab cell keys when column-pivoting (Task 2.5)", () => {
    const crosstabConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: ["sale_month"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    };
    const rawRows = [
      { hotel_name: "A", sale_month: "Jan 2025", sum_net_amount: 500 },
      { hotel_name: "A", sale_month: "Feb 2025", sum_net_amount: 700 },
      { hotel_name: "B", sale_month: "Jan 2025", sum_net_amount: 300 },
      { hotel_name: "B", sale_month: "Feb 2025", sum_net_amount: 900 },
    ];
    const result = formatPivotResults(rawRows, crosstabConfig);

    // Headers (after the row dimension) match crosstab cell keys.
    expect(result.headers).toContain("Jan 2025");
    expect(result.headers).toContain("Feb 2025");

    // Grand totals are now keyed by the same crosstab keys, with weighted
    // (here: SUM) totals across hotels per month.
    expect(result.grandTotals["Jan 2025"].value).toBe(800); // 500 + 300
    expect(result.grandTotals["Feb 2025"].value).toBe(1600); // 700 + 900

    // No header should resolve to "—" via the engine — every header
    // returned has a matching grand total cell.
    for (const header of result.headers.slice(1)) {
      expect(result.grandTotals[header]).toBeDefined();
      expect(result.grandTotals[header].formatted).not.toBe("—");
    }
  });

  it("grand totals key by `${colKey} | ${alias}` with multiple values (Task 2.5)", () => {
    const multiConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: ["sale_month"],
      values: [
        { field: "net_amount", aggregation: "sum" },
        { field: "net_amount", aggregation: "count" },
      ],
    };
    const rawRows = [
      {
        hotel_name: "A",
        sale_month: "Jan 2025",
        sum_net_amount: 500,
        count_net_amount: 5,
      },
      {
        hotel_name: "B",
        sale_month: "Jan 2025",
        sum_net_amount: 300,
        count_net_amount: 3,
      },
    ];
    const result = formatPivotResults(rawRows, multiConfig);

    // Cell keys + grand-total keys must match the multi-value composer.
    expect(result.grandTotals["Jan 2025 | sum_net_amount"].value).toBe(800);
    expect(result.grandTotals["Jan 2025 | count_net_amount"].value).toBe(8);
  });
});

// ─── FX-03 / D-17 / Pitfall 4 — saved-pivot back-compat + dual-emit substrate ─
//
// Phase 9.1 introduces dual-emit (native + GBP + currency_key) for analytics
// SUM(net_amount) sites. The pivot engine's contract per D-17 is:
//   1. PRESERVE the field id "net_amount" (and "booking_fee") so saved pivots
//      in production — which serialise {field: "net_amount", aggregation: ...}
//      into JSON — keep resolving without a saved-pivot rewrite (Pitfall 4).
//   2. ADD GBP + currency_key sibling columns to the SQL row so plan 09.1-07
//      can dispatch native-vs-GBP cell rendering per D-10.
//
// The tests below pin both halves: ALLOWED_COLUMNS still maps "net_amount" to
// the original native expression (D-17), and buildPivotSQL emits the new
// `<alias>_gbp` + `currency_key_<field>` companions whenever a value config
// references a currency-typed field.

describe("FX-03 / D-17 / Pitfall 4 — saved-pivot field id back-compat", () => {
  it("ALLOWED_COLUMNS still maps 'net_amount' to the native sales_records expression", () => {
    // Saved pivots in prod reference the field id `net_amount` directly. Any
    // change to this id (to e.g. `net_amount_native`) silently breaks every
    // saved pivot that has been emailed/exported and reloaded later. D-17
    // says preserve the id even though the SQL contract evolves.
    expect(ALLOWED_COLUMNS.get("net_amount")).toBe(
      "sales_records.net_amount::numeric",
    );
    // booking_fee gets the same back-compat treatment — it's also a
    // currency-typed metric saved pivots reference by id.
    expect(ALLOWED_COLUMNS.get("booking_fee")).toContain(
      "sales_records.net_amount::numeric",
    );
  });

  it("CURRENCY_GBP_COLUMNS exposes the GBP companion expression for both currency fields", () => {
    expect(CURRENCY_GBP_COLUMNS.get("net_amount")).toBe(
      "sales_records.net_amount_gbp::numeric",
    );
    expect(CURRENCY_GBP_COLUMNS.get("booking_fee")).toContain(
      "sales_records.net_amount_gbp::numeric",
    );
    expect(CURRENCY_GBP_COLUMNS.get("booking_fee")).toContain(
      "sales_records.is_weknow_fee = true",
    );
  });

  it("isCurrencyField returns true for net_amount + booking_fee, false otherwise", () => {
    expect(isCurrencyField("net_amount")).toBe(true);
    expect(isCurrencyField("booking_fee")).toBe(true);
    expect(isCurrencyField("product_name")).toBe(false);
    expect(isCurrencyField("sale_month")).toBe(false);
  });

  it("gbpAlias + currencyKeyAlias compose stable companion names", () => {
    // Stable shape so renderer code in plan 09.1-07 can derive cell keys
    // without inspecting the SQL — pure function of (agg, field).
    expect(gbpAlias("sum", "net_amount")).toBe("sum_net_amount_gbp");
    expect(gbpAlias("avg", "net_amount")).toBe("avg_net_amount_gbp");
    expect(gbpAlias("sum", "booking_fee")).toBe("sum_booking_fee_gbp");
    expect(currencyKeyAlias("net_amount")).toBe("currency_key_net_amount");
    expect(currencyKeyAlias("booking_fee")).toBe("currency_key_booking_fee");
  });

  it("a saved pivot row keyed on field id 'net_amount' still resolves to a non-empty cell", () => {
    // Simulates a pre-FX-03 saved pivot config being re-loaded post-deploy.
    // The pivot config still references `net_amount` (D-17 — id preserved),
    // and formatPivotResults must produce a cell at the same alias the saved
    // pivot would look up (`sum_net_amount`).
    const savedPivot: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    };
    // Driver-shape row carries the new companions alongside the legacy
    // `sum_net_amount` alias — saved pivot still finds its cell at the
    // legacy alias, while plan 09.1-07's renderer can reach for the GBP
    // sibling and currency_key when it lands.
    const rawRows = [
      {
        hotel_name: "Hotel A",
        sum_net_amount: 1000,
        sum_net_amount_gbp: 800,
        currency_key_net_amount: "EUR",
      },
    ];
    const result = formatPivotResults(rawRows, savedPivot);
    expect(result.rows[0].cells["sum_net_amount"]).toBeDefined();
    expect(result.rows[0].cells["sum_net_amount"].value).toBe(1000);
    expect(result.rows[0].cells["sum_net_amount"].formatted).not.toBe("");
  });

  it("buildPivotSQL emits sum_net_amount_gbp + currency_key_net_amount alongside sum_net_amount", () => {
    // Substrate for renderer dispatch (plan 09.1-07): the SQL row now carries
    // (sum_net_amount, sum_net_amount_gbp, currency_key_net_amount) for every
    // pivot that aggregates the net_amount metric.
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    // Primary alias preserved (D-17): saved pivots resolve their cell here.
    expect(sql).toContain('AS "sum_net_amount"');
    // GBP companion: SUM over the net_amount_gbp column.
    expect(sql).toContain("sales_records.net_amount_gbp::numeric");
    expect(sql).toContain('AS "sum_net_amount_gbp"');
    // currency_key resolver per D-10.
    expect(sql).toContain("COUNT(DISTINCT sales_records.currency)");
    expect(sql).toContain('AS "currency_key_net_amount"');
  });

  it("buildPivotSQL emits the same dual-emit shape for booking_fee (FILTER (WHERE is_weknow_fee))", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "booking_fee", aggregation: "sum" }],
    });
    expect(sql).toContain('AS "sum_booking_fee"');
    expect(sql).toContain('AS "sum_booking_fee_gbp"');
    expect(sql).toContain('AS "currency_key_booking_fee"');
    // currency_key for booking_fee scopes to fee rows so the resolver tracks
    // fee-only cohorts (a sales-only cohort would compute a meaningless key).
    expect(sql).toMatch(
      /COUNT\(DISTINCT sales_records\.currency\) FILTER \(WHERE sales_records\.is_weknow_fee = true\)/,
    );
  });

  it("buildPivotSQL skips dual-emit for COUNT aggregations (count is currency-agnostic)", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "count" }],
    });
    // Count alias preserved.
    expect(sql).toContain('AS "count_net_amount"');
    // No GBP arm or currency_key for count — would be meaningless to count
    // "rows in GBP" and waste cycles.
    expect(sql).not.toContain('AS "count_net_amount_gbp"');
    expect(sql).not.toContain('AS "currency_key_net_amount"');
  });

  it("buildPivotSQL skips dual-emit for non-currency value configs", () => {
    // Currently the schema's only currency value-fields are net_amount +
    // booking_fee. If a future config tries to aggregate a hypothetical
    // non-currency metric (e.g., a row count promoted to a metric), the
    // engine MUST NOT emit GBP companions — there's no sales_records
    // counterpart and the SQL would fail to compile.
    //
    // This test pins the contract via isCurrencyField + the absence of GBP
    // emissions in a pivot whose only metric is a count of net_amount.
    const sql = buildPivotSQL({
      rowFields: ["product_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "count" }],
    });
    expect(sql).not.toContain("net_amount_gbp");
    expect(sql).not.toContain("currency_key");
  });

  it("pivot row carries net_amount + net_amount_gbp + currency_key for renderer dispatch (plan 09.1-07)", () => {
    // End-to-end SQL substrate check: a pivot SELECT with a SUM(net_amount)
    // metric MUST project the three columns the renderer dispatch in plan
    // 09.1-07 will read. Saved pivots that have not been resaved post-deploy
    // continue to read `sum_net_amount` and see native sums; the renderer
    // can additionally pick `sum_net_amount_gbp` + `currency_key_net_amount`
    // to flip cells in single-currency cohorts.
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: ["sale_month"],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    expect(sql).toContain('AS "sum_net_amount"');
    expect(sql).toContain('AS "sum_net_amount_gbp"');
    expect(sql).toContain('AS "currency_key_net_amount"');
  });
});

// ─── FX-03 / D-10 — formatCell auto-pick (plan 09.1-07) ─────────────────────

describe("FX-03 / D-10 — formatCell auto-pick (plan 09.1-07)", () => {
  const config: PivotConfig = {
    rowFields: ["hotel_name"],
    columnFields: [],
    values: [{ field: "net_amount", aggregation: "sum" }],
  };

  it("single-currency cohort: cell formats with native symbol (EUR → €)", () => {
    // currency_key_net_amount = 'EUR' on every row → grand total + per-cell
    // both render with the EUR symbol via formatNativeCurrency. The primary
    // alias (sum_net_amount) carries the native sum; sum_net_amount_gbp is
    // present too but ignored when currency_key is set.
    const rawRows = [
      {
        hotel_name: "Paris",
        sum_net_amount: 1000,
        sum_net_amount_gbp: 850,
        currency_key_net_amount: "EUR",
      },
      {
        hotel_name: "Berlin",
        sum_net_amount: 2000,
        sum_net_amount_gbp: 1700,
        currency_key_net_amount: "EUR",
      },
    ];
    const result = formatPivotResults(rawRows, config);
    expect(result.rows[0].cells["sum_net_amount"].formatted).toContain("€");
    expect(result.rows[0].cells["sum_net_amount"].value).toBe(1000); // native arm
    expect(result.grandTotals["sum_net_amount"].formatted).toContain("€");
    expect(result.grandTotals["sum_net_amount"].value).toBe(3000); // native sum
  });

  it("multi-currency cohort: cell formats with GBP (£) using the GBP arm", () => {
    // currency_key_net_amount differs across rows → grand-total bucket is
    // multi-currency → fall back to formatCurrency. Per-cell each row's
    // own currency_key is set, so per-cell stays native; but the grand total
    // uses the GBP arm because the bucket spans EUR + GBP.
    const rawRows = [
      {
        hotel_name: "Paris",
        sum_net_amount: 1000,
        sum_net_amount_gbp: 850,
        currency_key_net_amount: "EUR",
      },
      {
        hotel_name: "London",
        sum_net_amount: 1500,
        sum_net_amount_gbp: 1500,
        currency_key_net_amount: "GBP",
      },
    ];
    const result = formatPivotResults(rawRows, config);
    // Grand total: bucket is multi-currency → formatCurrency (GBP) on the
    // GBP arm sum (850 + 1500 = 2350).
    expect(result.grandTotals["sum_net_amount"].formatted).toContain("£");
    expect(result.grandTotals["sum_net_amount"].value).toBe(2350);
  });

  it("back-compat: rows without dual-emit substrate render as before (GBP-pinned)", () => {
    // D-17 / Pitfall 4 back-compat: a saved-pivot caller that has not
    // migrated to read `<alias>_gbp` + currency_key columns continues to see
    // the same numbers and the same GBP-pinned format. This guards against
    // a silent regression in pivot consumers that bypass buildPivotSQL.
    const rawRows = [
      { hotel_name: "A", sum_net_amount: 1000 },
      { hotel_name: "B", sum_net_amount: 3000 },
    ];
    const result = formatPivotResults(rawRows, config);
    expect(result.rows[0].cells["sum_net_amount"].formatted).toContain("£");
    expect(result.grandTotals["sum_net_amount"].formatted).toContain("£");
    expect(result.grandTotals["sum_net_amount"].value).toBe(4000);
  });

  it("count aggregation skips the dispatch (currency-agnostic)", () => {
    const countConfig: PivotConfig = {
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "count" }],
    };
    const rawRows = [
      {
        hotel_name: "Paris",
        count_net_amount: 10,
        // Even with currency_key set, count must render as a plain number,
        // not formatted with a currency symbol.
        currency_key_net_amount: "EUR",
      },
    ];
    const result = formatPivotResults(rawRows, countConfig);
    expect(result.rows[0].cells["count_net_amount"].formatted).not.toContain("€");
    expect(result.rows[0].cells["count_net_amount"].formatted).not.toContain("£");
    expect(result.rows[0].cells["count_net_amount"].value).toBe(10);
  });
});

// ─── Phase 9.1 gap closure (WR-09) — currency_key symmetry ──────────────────
//
// Pre-fix: the comment block at currency_key emission only said "apply the
// same FILTER as booking_fee CASE expression bakes" — leaving open whether
// net_amount should also have a filter. The intentional asymmetry (booking_fee
// filters because its SUM wraps a CASE WHEN; net_amount doesn't filter because
// its SUM is raw) is load-bearing — emitting a filter on net_amount would
// drop legitimate cross-currency sales rows from COUNT(DISTINCT currency)
// and produce a misleading single-currency key for a multi-currency cohort.
//
// Post-fix: tightened comment + these two specs pin the SQL shape so a future
// refactor that "tidies up" the asymmetric handling trips here.
describe("WR-09 currency_key symmetry", () => {
  it("booking_fee currency_key applies the IS_FEE filter (rowset matches the SUM's non-zero population)", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "booking_fee", aggregation: "sum" }],
    });
    // FILTER (WHERE is_weknow_fee = true) must wrap BOTH the COUNT(DISTINCT)
    // and the MIN() inside the currency_key CASE — together they identify
    // the single shared currency only across rows that contribute non-zero
    // to the booking_fee SUM. Without the filter, an EUR sales row sitting
    // alongside a GBP fee row would inflate COUNT(DISTINCT) to 2 and drop
    // currency_key to NULL even though the fee SUM is GBP-only.
    expect(sql).toMatch(
      /COUNT\(DISTINCT sales_records\.currency\) FILTER \(WHERE sales_records\.is_weknow_fee = true\)/,
    );
    expect(sql).toMatch(
      /MIN\(sales_records\.currency\) FILTER \(WHERE sales_records\.is_weknow_fee = true\)/,
    );
  });

  it("net_amount currency_key does NOT apply any filter (SUM is unfiltered, key must match)", () => {
    const sql = buildPivotSQL({
      rowFields: ["hotel_name"],
      columnFields: [],
      values: [{ field: "net_amount", aggregation: "sum" }],
    });
    // The unfiltered shape: COUNT(DISTINCT ...) = 1 with no FILTER clause.
    // If a future change adds a FILTER here, a cross-currency-on-non-fee-rows
    // cohort that the SUM correctly aggregates as multi-currency would drop
    // its currency_key to NULL — which the renderer ALREADY handles, but
    // the contract change risks subtle disagreements between the SUM's
    // population and the key's population on cohorts that mix fee and
    // non-fee rows.
    expect(sql).toMatch(/COUNT\(DISTINCT sales_records\.currency\)\s*=\s*1/);
    expect(sql).not.toMatch(
      /COUNT\(DISTINCT sales_records\.currency\) FILTER/,
    );
    expect(sql).not.toMatch(/MIN\(sales_records\.currency\) FILTER/);
  });

  it("comment block flags the asymmetry as intentional (WR-09 / Phase 9.1)", () => {
    // The comment is the operator-facing guardrail. If a refactor strips
    // the explanation, the next reviewer might "fix" the asymmetry by
    // making the two paths uniform — silently breaking one of the two
    // population-tracking contracts. Pinning a marker here forces a
    // deliberate ack-or-replace.
    //
    // Read the source and check for the WR-09 marker. We don't import fs
    // statically (project convention is async-only); use require for the
    // sync read path that vitest is fine with.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("node:fs");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("node:path");
    const src = fs.readFileSync(
      path.resolve(__dirname, "./pivot-engine.ts"),
      "utf8",
    );
    expect(src).toMatch(/WR-09/);
    expect(src).toMatch(/asymmetry is intentional/i);
  });
});
