import {
  pgTable,
  text,
  timestamp,
  boolean,
  doublePrecision,
  uuid,
  integer,
  jsonb,
  numeric,
  primaryKey,
  uniqueIndex,
  unique,
  index,
  date,
  time,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";

// =============================================================================
// Better Auth tables
// These match the schema generated by Better Auth 1.5 with the admin plugin.
// Do NOT modify column names — Better Auth expects these exact names.
// =============================================================================

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  // Admin plugin columns
  role: text("role").default("member"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  // Phase 1 — user classification (internal staff vs external hotel users)
  userType: text("user_type", { enum: ["internal", "external"] })
    .notNull()
    .default("internal"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// =============================================================================
// Application tables
// =============================================================================

// Phase 4.1 — Kiosk Config Groups (defined before kiosks for FK reference)
export const kioskConfigGroups = pgTable("kiosk_config_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// App settings key-value store (board ID persistence, per D-13)
export const appSettings = pgTable("app_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Pipeline stages — FLOAT8 for position to avoid batch-update race conditions
export const pipelineStages = pgTable("pipeline_stages", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  position: doublePrecision("position").notNull(),
  color: text("color"),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Kiosks
export const kiosks = pgTable("kiosks", {
  id: uuid("id").primaryKey().defaultRandom(),
  kioskId: text("kiosk_id").notNull().unique(),
  outletCode: text("outlet_code"),
  hardwareModel: text("hardware_model"),
  hardwareSerialNumber: text("hardware_serial_number"),
  softwareVersion: text("software_version"),
  cmsConfigStatus: text("cms_config_status"),
  installationDate: timestamp("installation_date"),
  deploymentPhaseTags: jsonb("deployment_phase_tags").$type<string[]>(),
  maintenanceFee: numeric("maintenance_fee"),
  freeTrialStatus: boolean("free_trial_status").default(false),
  freeTrialEndDate: timestamp("free_trial_end_date"),
  regionGroup: text("region_group"),
  pipelineStageId: uuid("pipeline_stage_id").references(() => pipelineStages.id),
  kioskConfigGroupId: uuid("kiosk_config_group_id").references(() => kioskConfigGroups.id),
  notes: text("notes"),
  customFields: jsonb("custom_fields").$type<Record<string, string>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
});

// Locations
export const locations = pgTable("locations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  address: text("address"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  starRating: integer("star_rating"),
  roomCount: integer("room_count"),
  keyContacts: jsonb("key_contacts").$type<
    Array<{ name: string; role: string; email: string; phone: string }>
  >(),
  customerCode: text("customer_code"),
  // Phase 1 M4 — outlet code is the stable identifier for a hotel in the
  // sales CSV. Data-dashboard's hotel_metadata_cache used it as the PK; we
  // mirror that on locations so CSV rows can FK-resolve to locations.id.
  outletCode: text("outlet_code").unique(),
  hotelGroup: text("hotel_group"),
  operatingGroupId: uuid("operating_group_id").references(() => hotelGroups.id, { onDelete: "set null" }),
  sourcedBy: text("sourced_by"),
  bankingDetails: jsonb("banking_details"),
  contractValue: numeric("contract_value"),
  contractStartDate: timestamp("contract_start_date"),
  contractEndDate: timestamp("contract_end_date"),
  contractTerms: text("contract_terms"),
  contractDocuments: jsonb("contract_documents").$type<
    Array<{ fileName: string; s3Key: string; uploadedAt: string }>
  >(),
  maintenanceFee: numeric("maintenance_fee"),
  freeTrialEndDate: timestamp("free_trial_end_date"),
  hardwareAssets: text("hardware_assets"),
  notes: text("notes"),
  // Phase 4.1 — new location fields (D-22)
  region: text("region"),
  locationGroup: text("location_group"),
  internalPocId: text("internal_poc_id").references(() => user.id),
  status: text("status"),
  // Kiosk config group lives on the location: each hotel belongs to one
  // group (imported from Monday column 1466686598). Nullable FK + ON DELETE
  // SET NULL so removing a group does not cascade-delete locations.
  kioskConfigGroupId: uuid("kiosk_config_group_id").references(
    () => kioskConfigGroups.id,
    { onDelete: "set null" },
  ),
  customFields: jsonb("custom_fields").$type<Record<string, string>>(),
  // Phase 1 M1 Task 1.5 — hotel dimension fields (ported from data-dashboard analytics schema)
  numRooms: integer("num_rooms"),
  hotelAddress: text("hotel_address"),
  liveDate: timestamp("live_date"),
  launchPhase: text("launch_phase"),
  keyContactName: text("key_contact_name"),
  keyContactEmail: text("key_contact_email"),
  financeContact: text("finance_contact"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
});

// Kiosk assignments — temporal join table for assignment history
export const kioskAssignments = pgTable("kiosk_assignments", {
  id: uuid("id").primaryKey().defaultRandom(),
  kioskId: uuid("kiosk_id")
    .notNull()
    .references(() => kiosks.id),
  locationId: uuid("location_id")
    .notNull()
    .references(() => locations.id),
  assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
  unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
  reason: text("reason"),
  assignedBy: text("assigned_by").notNull(),
  assignedByName: text("assigned_by_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// Audit log — append-only with denormalized actor/entity names
export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  actorId: text("actor_id"),
  actorName: text("actor_name"),
  entityType: text("entity_type").notNull(),
  // text (not uuid) — entity IDs are heterogeneous across types: kiosks /
  // installations / locations are uuid, but Better Auth user IDs are random
  // 32-char strings. uuid would reject the user-typed audit rows.
  entityId: text("entity_id").notNull(),
  entityName: text("entity_name"),
  action: text("action").notNull(),
  field: text("field"),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// User views — saved filter/sort/group configurations
export const userViews = pgTable("user_views", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  name: text("name").notNull(),
  entityType: text("entity_type").notNull(),
  viewType: text("view_type").notNull().default("table"),
  config: jsonb("config")
    .$type<{
      filters?: Record<string, unknown>;
      sort?: Record<string, unknown>;
      groupBy?: string;
      columns?: string[];
    }>()
    .notNull(),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// =============================================================================
// Phase 3 — Installation tables
// =============================================================================

// Installations — project-level grouping of kiosks with date range and status
export const installations = pgTable("installations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  region: text("region"),
  status: text("status").notNull().default("planned"),
  plannedStart: timestamp("planned_start", { withTimezone: true }),
  plannedEnd: timestamp("planned_end", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Milestones — key dates on an installation (contract signing, go-live, etc.)
export const milestones = pgTable("milestones", {
  id: uuid("id").primaryKey().defaultRandom(),
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  targetDate: timestamp("target_date", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// installationKiosks — join table linking installations to kiosks
export const installationKiosks = pgTable("installation_kiosks", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  kioskId: uuid("kiosk_id")
    .notNull()
    .references(() => kiosks.id, { onDelete: "cascade" }),
}, (t) => [primaryKey({ columns: [t.installationId, t.kioskId] })]);

// installationMembers — join table for team members on an installation
export const installationMembers = pgTable("installation_members", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").notNull(),
}, (t) => [primaryKey({ columns: [t.installationId, t.userId] })]);

// =============================================================================
// Phase 4 — Product/Provider tables
// =============================================================================

// Products — distinct product types (e.g. Transfers, Tours & Activities)
export const products = pgTable("products", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Providers — companies providing products (e.g. Uber, TUI Musement)
export const providers = pgTable("providers", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Location products — per-hotel product availability, provider assignment, and commission tiers
export const locationProducts = pgTable("location_products", {
  id: uuid("id").primaryKey().defaultRandom(),
  locationId: uuid("location_id").notNull().references(() => locations.id),
  productId: uuid("product_id").notNull().references(() => products.id),
  providerId: uuid("provider_id").references(() => providers.id),
  availability: text("availability").notNull().default("unavailable"),
  commissionTiers: jsonb("commission_tiers").$type<Array<{
    effectiveFrom: string;
    tiers: Array<{ minRevenue: number; maxRevenue: number | null; rate: number }>;
  }>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Commission ledger — per-sale commission calculation records with tier breakdown
export const commissionLedger = pgTable(
  "commission_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    salesRecordId: uuid("sales_record_id")
      .notNull()
      .references(() => salesRecords.id, { onDelete: "cascade" }),
    locationProductId: uuid("location_product_id")
      .references(() => locationProducts.id, { onDelete: "set null" }),
    grossAmount: numeric("gross_amount", { precision: 12, scale: 2 }).notNull(),
    commissionableAmount: numeric("commissionable_amount", { precision: 12, scale: 2 }).notNull(),
    commissionAmount: numeric("commission_amount", { precision: 12, scale: 2 }).notNull(),
    tierBreakdown: jsonb("tier_breakdown")
      .$type<Array<{ tierRate: number; revenueInTier: number; commission: number }>>()
      .notNull(),
    tierVersionEffectiveFrom: text("tier_version_effective_from").notNull(),
    calculatedAt: timestamp("calculated_at", { withTimezone: true }).defaultNow().notNull(),
    isReversal: boolean("is_reversal").notNull().default(false),
  },
  (t) => ({
    bySalesRecord: index("cl_sales_record_idx").on(t.salesRecordId),
    byLocationProductReversal: index("cl_location_product_idx").on(t.locationProductId, t.isReversal),
  }),
);

// Phase 4.1 note: appSettings already declared above (line ~88).

// Duplicate dismissals — admin marks a pair of locations as "not duplicates";
// stored canonical-ordered (locationAId < locationBId lexicographically) so
// the UNIQUE constraint collapses both directions of the pair.
export const duplicateDismissals = pgTable(
  "duplicate_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    locationAId: uuid("location_a_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    locationBId: uuid("location_b_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    dismissedBy: text("dismissed_by").notNull(),
    dismissedByName: text("dismissed_by_name").notNull(),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    uniqueIndex("duplicate_dismissals_pair_idx").on(t.locationAId, t.locationBId),
  ]
);

// =============================================================================
// Phase 1 — User scopes (dimension-based access scoping)
// =============================================================================

// INVARIANT: users with userType='external' MUST have >=1 row in userScopes.
// Enforced in invite-accept handler (src/lib/auth/invite.ts) and in scopedQuery().
// Not enforced at DB layer because insert-ordering makes a CHECK constraint impractical.
export const userScopes = pgTable(
  "user_scopes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    dimensionType: text("dimension_type", {
      enum: [
        "hotel_group",
        "location",
        "region",
        "product",
        "provider",
        "location_group",
      ],
    }).notNull(),
    dimensionId: text("dimension_id").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    createdBy: text("created_by").references(() => user.id),
  },
  (t) => ({
    uniq: unique().on(t.userId, t.dimensionType, t.dimensionId),
    byUser: index("user_scopes_user_idx").on(t.userId),
  })
);

// =============================================================================
// Phase 1 M1 Task 1.6 — Analytics dimension tables
// Ported from data-dashboard. These enable scoped analytics: a user with
// userScopes.dimensionType='hotel_group' sees only locations belonging to that
// hotel_group via the membership join tables below.
//
// NOTE: free-text columns `locations.region`, `locations.hotel_group`,
// `locations.location_group` coexist with these dimension tables — the tables
// are used for scoped joins while the free-text columns remain for legacy
// input / unnormalised data.
// =============================================================================

// Markets — top-level geographic grouping (e.g. UK & Ireland, Continental Europe).
// Regions belong to a market, enabling hierarchical geo drill-down.
export const markets = pgTable("markets", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  code: text("code"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Hotel groups — hierarchical grouping of hotel locations (e.g. Dalata Hotels).
// Supports nesting via self-referential parentGroupId.
export const hotelGroups = pgTable("hotel_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  parentGroupId: uuid("parent_group_id").references(
    (): AnyPgColumn => hotelGroups.id,
    { onDelete: "set null" },
  ),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Regions — geographic grouping of locations (e.g. UK, EU, North America).
export const regions = pgTable("regions", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  code: text("code"),
  marketId: uuid("market_id").references(() => markets.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Location groups — arbitrary groupings for scoped access (e.g. "City Centre Hotels").
export const locationGroups = pgTable("location_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  description: text("description"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Membership join tables (many-to-many between locations and dimensions).
// Composite PK on (locationId, dimensionId) prevents duplicates.
// Cascade delete from both sides keeps memberships in sync.

export const locationHotelGroupMemberships = pgTable(
  "location_hotel_group_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    hotelGroupId: uuid("hotel_group_id")
      .notNull()
      .references(() => hotelGroups.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.hotelGroupId] }),
    byHotelGroup: index("lhg_hotel_group_idx").on(t.hotelGroupId),
  }),
);

export const locationRegionMemberships = pgTable(
  "location_region_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    regionId: uuid("region_id")
      .notNull()
      .references(() => regions.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.regionId] }),
    byRegion: index("lrm_region_idx").on(t.regionId),
  }),
);

export const locationGroupMemberships = pgTable(
  "location_group_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    locationGroupId: uuid("location_group_id")
      .notNull()
      .references(() => locationGroups.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.locationGroupId] }),
    byLocationGroup: index("lgm_location_group_idx").on(t.locationGroupId),
  }),
);

// =============================================================================
// Phase 1 M1 Task 1.7 — Sales-data pipeline tables
// Ported from data-dashboard CSV shape. Three tables:
//   - salesImports    — one row per CSV upload (metadata + status)
//   - importStagings  — per-row staging area pre-commit (validation/rollback)
//   - salesRecords    — committed fact table (per transaction)
//
// Ordering note: salesImports declared FIRST (no forward FKs); importStagings
// next (references salesImports); salesRecords last (references salesImports).
// Only salesRecords.importId points AT salesImports — not reverse — so no
// circular dependency at declaration time.
//
// NOTE: drizzle-kit's `text(..., { enum: [...] })` helper enforces the enum
// at the TypeScript type level only. The migration (0008) hand-appends CHECK
// constraints at the DB layer for `sales_imports.status` and
// `import_stagings.status`, matching the pattern established by 0003 and 0005.
// =============================================================================

export const salesImports = pgTable("sales_imports", {
  id: uuid("id").primaryKey().defaultRandom(),
  filename: text("filename").notNull(),
  // Unique so duplicate uploads are caught at the DB layer (not just app-level).
  sourceHash: text("source_hash").notNull().unique(),
  uploadedBy: text("uploaded_by").notNull().references(() => user.id),
  uploadedAt: timestamp("uploaded_at").notNull().defaultNow(),
  rowCount: integer("row_count").notNull().default(0),
  dateRangeStart: date("date_range_start"),
  dateRangeEnd: date("date_range_end"),
  status: text("status", { enum: ["staging", "committed", "failed", "rolled_back"] })
    .notNull()
    .default("staging"),
  errors: jsonb("errors"),
});

export const importStagings = pgTable(
  "import_stagings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id")
      .notNull()
      .references(() => salesImports.id, { onDelete: "cascade" }),
    rowNumber: integer("row_number").notNull(),
    rawRow: jsonb("raw_row").notNull(),
    parsedRow: jsonb("parsed_row"),
    status: text("status", { enum: ["pending", "valid", "invalid", "committed"] })
      .notNull()
      .default("pending"),
    validationErrors: jsonb("validation_errors"),
  },
  (t) => ({
    byImport: index("staging_import_idx").on(t.importId),
  }),
);

export const salesRecords = pgTable(
  "sales_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id").references(() => salesImports.id, { onDelete: "set null" }),
    saleRef: text("sale_ref").notNull(),
    refNo: text("ref_no"),
    transactionDate: date("transaction_date").notNull(),
    transactionTime: time("transaction_time"),
    locationId: uuid("location_id").notNull().references(() => locations.id),
    productId: uuid("product_id").notNull().references(() => products.id),
    providerId: uuid("provider_id").references(() => providers.id),
    quantity: integer("quantity").notNull().default(1),
    grossAmount: numeric("gross_amount", { precision: 12, scale: 2 }).notNull(),
    netAmount: numeric("net_amount", { precision: 12, scale: 2 }),
    discountCode: text("discount_code"),
    discountAmount: numeric("discount_amount", { precision: 12, scale: 2 }),
    bookingFee: numeric("booking_fee", { precision: 12, scale: 2 }),
    saleCommission: numeric("sale_commission", { precision: 12, scale: 2 }),
    currency: text("currency").notNull().default("GBP"),
    customerCode: text("customer_code"),
    customerName: text("customer_name"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    saleRefIdx: index("sales_sale_ref_idx").on(t.saleRef),
    locDateIdx: index("sales_loc_date_idx").on(t.locationId, t.transactionDate),
    prodDateIdx: index("sales_prod_date_idx").on(t.productId, t.transactionDate),
    provDateIdx: index("sales_prov_date_idx").on(t.providerId, t.transactionDate),
    txnDateIdx: index("sales_txn_date_idx").on(t.transactionDate),
    uniq: unique().on(t.saleRef, t.transactionDate),
  }),
);

// =============================================================================
// Phase 1 M1 Task 1.8 — Remaining analytics tables (ported from data-dashboard)
//
// Source migrations in /Users/vedant/Work/WeKnowGroup/data-dashboard/supabase/migrations/:
//   - 20260223_add_outlet_exclusions.sql          → outletExclusions
//   - 20260317_phase4_trend_builder.sql           → eventCategories, businessEvents,
//                                                   analyticsSavedViews (saved_views),
//                                                   weatherCache
// Inferred (no Supabase migration — see task 1.8 in docs/plans):
//   - analyticsPresets — saved filter/dimension configs (shape per design doc).
//   - eventLog         — lightweight analytics usage tracking.
//
// Adaptations vs Supabase source:
//   - `auth.users(id) uuid` → `user.id text` (Better Auth text IDs).
//   - Dropped Supabase RLS policies / is_admin() / auth.uid() references;
//     scoping is handled in our scopedQuery() layer.
//   - `saved_views.series_config` (jsonb) → `analyticsSavedViews.config` +
//     added `viewType` (trend|pivot|heatmap) enum per design doc.
//   - CHECK constraints for text({enum}) columns are hand-appended in the
//     0009 migration (same pattern as 0003/0005/0008).
// =============================================================================

// outletExclusions — admin-managed outlet exclusion rules with exact/regex patterns.
export const outletExclusions = pgTable(
  "outlet_exclusions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    outletCode: text("outlet_code").notNull(),
    patternType: text("pattern_type", { enum: ["exact", "regex"] })
      .notNull()
      .default("exact"),
    label: text("label"),
    createdBy: text("created_by").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    uniq: unique().on(t.outletCode, t.patternType),
    byPatternType: index("outlet_exclusions_pattern_type_idx").on(t.patternType),
    byOutletCode: index("outlet_exclusions_outlet_code_idx").on(t.outletCode),
  }),
);

// analyticsPresets — saved filter/dimension configs (per-user, shareable).
// Inferred shape — no Supabase migration; see M1 Task 1.8 notes.
export const analyticsPresets = pgTable("analytics_presets", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  ownerId: text("owner_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  config: jsonb("config").notNull(),
  isShared: boolean("is_shared").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// analyticsSavedViews — per-user saved analytics view configurations
// (trend / pivot / heatmap). Ported from data-dashboard `saved_views` with
// `viewType` added per our design doc; Supabase `series_config` → `config`.
export const analyticsSavedViews = pgTable(
  "analytics_saved_views",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    viewType: text("view_type", { enum: ["trend", "pivot", "heatmap"] }).notNull(),
    config: jsonb("config").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    uniqOwnerName: unique().on(t.ownerId, t.name),
    byOwner: index("analytics_saved_views_owner_idx").on(t.ownerId),
  }),
);

// eventCategories — taxonomy for business events (Promotion, Holiday, ...).
export const eventCategories = pgTable("event_categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  color: text("color").notNull().default("#666666"),
  isCore: boolean("is_core").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// businessEvents — annotatable business events shown on trend charts.
export const businessEvents = pgTable(
  "business_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    title: text("title").notNull(),
    description: text("description"),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => eventCategories.id),
    startDate: date("start_date").notNull(),
    endDate: date("end_date"),
    scopeType: text("scope_type", {
      enum: ["global", "hotel", "region", "hotel_group"],
    }),
    scopeValue: text("scope_value"),
    createdBy: text("created_by").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byDates: index("business_events_dates_idx").on(t.startDate, t.endDate),
  }),
);

// weatherCache — cache of weather API responses keyed by cacheKey (e.g.
// "loc:<locationId>:<date>"). Supabase source uses a single text PK cache_key
// which already gives us the composite-uniqueness property (locationId+date).
export const weatherCache = pgTable(
  "weather_cache",
  {
    cacheKey: text("cache_key").primaryKey(),
    dateFrom: date("date_from").notNull(),
    dateTo: date("date_to").notNull(),
    data: jsonb("data").notNull(),
    isForecast: boolean("is_forecast").notNull().default(false),
    cachedAt: timestamp("cached_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byCachedAt: index("weather_cache_cached_idx").on(t.cachedAt),
  }),
);

// =============================================================================
// Phase 1 M11.2 — Location performance flags
// Allows admins to flag underperforming locations for triage (relocate, monitor,
// or strategic_exception). Flags remain active until explicitly resolved.
// =============================================================================

export const locationFlags = pgTable("location_flags", {
  id: uuid("id").primaryKey().defaultRandom(),
  locationId: uuid("location_id")
    .notNull()
    .references(() => locations.id, { onDelete: "cascade" }),
  flagType: text("flag_type", { enum: ["relocate", "monitor", "strategic_exception"] }).notNull(),
  reason: text("reason"),
  actorId: text("actor_id")
    .notNull()
    .references(() => user.id),
  actorName: text("actor_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  resolvedBy: text("resolved_by").references(() => user.id),
  resolutionNote: text("resolution_note"),
});

// =============================================================================
// Phase 1 M12.2 — Experiment cohorts
// Allows users to define location cohorts, compare metrics against a control
// group (rest of portfolio or named locations), and overlay intervention dates.
// =============================================================================

export const experimentCohorts = pgTable("experiment_cohorts", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  description: text("description"),
  locationIds: jsonb("location_ids").$type<string[]>().notNull(),
  controlType: text("control_type", { enum: ["rest_of_portfolio", "named_control"] }).notNull().default("rest_of_portfolio"),
  controlLocationIds: jsonb("control_location_ids").$type<string[]>(),
  interventionDate: date("intervention_date"),
  createdBy: text("created_by").notNull().references(() => user.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// =============================================================================
// Phase 1 M13.2 — Insight-to-action workflow
// Action items derived from performance flags, data-quality issues, or manual
// creation. Tracks investigation, relocation, training, and equipment changes.
// =============================================================================

export const actionItems = pgTable("action_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  sourceType: text("source_type", { enum: ["flag", "manual", "data_quality"] }).notNull(),
  sourceId: text("source_id"),
  locationId: uuid("location_id").references(() => locations.id, { onDelete: "set null" }),
  actionType: text("action_type", { enum: ["investigation", "relocation", "training", "equipment_change"] }).notNull(),
  title: text("title").notNull(),
  description: text("description"),
  ownerId: text("owner_id").references(() => user.id, { onDelete: "set null" }),
  dueDate: date("due_date"),
  status: text("status", { enum: ["open", "in_progress", "resolved", "cancelled"] }).notNull().default("open"),
  outcomeNotes: text("outcome_notes"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().references(() => user.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// eventLog — lightweight analytics usage tracking. userId is nullable to
// support anonymous / system events (e.g. scheduled exports).
export const eventLog = pgTable(
  "event_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
    actionType: text("action_type").notNull(),
    metadata: jsonb("metadata"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byUser: index("event_log_user_idx").on(t.userId),
    byAction: index("event_log_action_idx").on(t.actionType),
    byOccurred: index("event_log_occurred_idx").on(t.occurredAt),
  }),
);
