import {
  pgTable,
  text,
  timestamp,
  boolean,
  doublePrecision,
  uuid,
  integer,
  jsonb,
  numeric,
  primaryKey,
  uniqueIndex,
  unique,
  index,
  date,
  time,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// =============================================================================
// Better Auth tables
// These match the schema generated by Better Auth 1.5 with the admin plugin.
// Do NOT modify column names — Better Auth expects these exact names.
// =============================================================================

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  // Admin plugin columns
  role: text("role").default("member"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  // Phase 1 — user classification (internal staff vs external hotel users)
  userType: text("user_type", { enum: ["internal", "external"] })
    .notNull()
    .default("internal"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// =============================================================================
// Application tables
// =============================================================================

// Phase 4.1 — Kiosk Config Groups (defined before kiosks for FK reference)
export const kioskConfigGroups = pgTable("kiosk_config_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// App settings key-value store (board ID persistence, per D-13)
export const appSettings = pgTable("app_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Pipeline stages — FLOAT8 for position to avoid batch-update race conditions
export const pipelineStages = pgTable("pipeline_stages", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  position: doublePrecision("position").notNull(),
  color: text("color"),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Kiosks
export const kiosks = pgTable("kiosks", {
  id: uuid("id").primaryKey().defaultRandom(),
  kioskId: text("kiosk_id").notNull().unique(),
  outletCode: text("outlet_code"),
  hardwareModel: text("hardware_model"),
  hardwareSerialNumber: text("hardware_serial_number"),
  softwareVersion: text("software_version"),
  cmsConfigStatus: text("cms_config_status"),
  installationDate: timestamp("installation_date"),
  deploymentPhaseTags: jsonb("deployment_phase_tags").$type<string[]>(),
  maintenanceFee: numeric("maintenance_fee"),
  freeTrialStatus: boolean("free_trial_status").default(false),
  freeTrialEndDate: timestamp("free_trial_end_date"),
  regionGroup: text("region_group"),
  pipelineStageId: uuid("pipeline_stage_id").references(() => pipelineStages.id),
  // Phase 7.6c — `kiosks.kiosk_config_group_id` was removed because the
  // grouping lives at the location level (Monday col 1466686598 →
  // `locations.kiosk_config_group_id`). Schema field dropped here; the DB
  // column is dropped by migration 0037, applied post-merge.
  // Internal POC / assignee — the user responsible for this kiosk. Nullable;
  // ON DELETE SET NULL in the migration so deleting a user doesn't cascade.
  internalPocId: text("internal_poc_id").references(() => user.id),
  notes: text("notes"),
  customFields: jsonb("custom_fields").$type<Record<string, string>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  // Phase 9 — alert silencing now lives on `locations` (the alert is hotel-
  // level, not kiosk-level — see migration 0045 + classify-locations.ts).
});

// Locations
export const locations = pgTable(
  "locations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    // Phase 7 (Plan B) — canonical normalised form of `name` used to detect
    // same-name location collisions across regions. Populated at write-time
    // by the Monday hotel importer (Plan B Task 2). Backfilled and given a
    // partial unique index by Plan D (Plan 07-04). Nullable until the
    // backfill runs.
    normalisedName: text("normalised_name"),
    address: text("address"),
    latitude: doublePrecision("latitude"),
    longitude: doublePrecision("longitude"),
    starRating: integer("star_rating"),
    roomCount: integer("room_count"),
    keyContacts: jsonb("key_contacts").$type<
      Array<{ name: string; role: string; email: string; phone: string }>
    >(),
    // Phase 7 Plan 07-06 — customer_code is the canonical hotel-level
    // identifier (the RPS account code mirrored from Monday's `mirror3__1`).
    // Nullable: placeholders (RTL "Ready to Launch", Heathrow pre-deployment)
    // and the LOCATION_NEEDED sentinel legitimately have no code. A partial
    // unique index over (primary_region_id, customer_code) WHERE NOT NULL
    // (migration 0040) enforces "one location per RPS account per region"
    // without blocking placeholders.
    customerCode: text("customer_code"),
    // Phase 7 Plan 07-06 — universal idempotency key for the Monday hotel /
    // Heathrow / Assets importers. Every Monday item has a stable id; this
    // is the ON CONFLICT target replacing the old (region, outlet_code)
    // compound. Partial-unique index in migration 0040.
    mondayItemId: text("monday_item_id"),
    // NetSuite ETL region scope (2026-04-24): each location belongs to exactly
    // one canonical region. Populated from kiosk assignments / memberships
    // during the 0022 migration; new rows must set this explicitly.
    primaryRegionId: uuid("primary_region_id")
      .notNull()
      .references(() => regions.id),
    hotelGroup: text("hotel_group"),
    operatingGroupId: uuid("operating_group_id").references(() => hotelGroups.id, { onDelete: "set null" }),
    sourcedBy: text("sourced_by"),
    bankingDetails: jsonb("banking_details"),
    contractValue: numeric("contract_value"),
    contractStartDate: timestamp("contract_start_date"),
    contractEndDate: timestamp("contract_end_date"),
    contractTerms: text("contract_terms"),
    contractDocuments: jsonb("contract_documents").$type<
      Array<{ fileName: string; s3Key: string; uploadedAt: string }>
    >(),
    maintenanceFee: numeric("maintenance_fee"),
    freeTrialEndDate: timestamp("free_trial_end_date"),
    hardwareAssets: text("hardware_assets"),
    notes: text("notes"),
    // Phase 4.1 — new location fields (D-22)
    // `region` (free-text) dropped in 0022 — use primaryRegionId + regions FK.
    locationGroup: text("location_group"),
    internalPocId: text("internal_poc_id").references(() => user.id),
    status: text("status"),
    // Location type — drives the Location Type analytics filter + the
    // unmapped-outlets admin page. NULL means "not yet categorised"; the
    // admin page surfaces those for manual assignment (default: airport).
    // 'internal' (D9 / Phase 7.1) marks refund-handling outlets excluded
    // from analytics by default.
    // Enforced via CHECK constraint in migration 0024 + 0034. The TS enum
    // here is informational — Drizzle does not write the CHECK from this
    // value, but it propagates the narrow union into LocationWithRelations.
    locationType: text("location_type", {
      enum: ["hotel", "retail_desk", "online", "airport", "hex_kiosk", "internal"],
    }),
    // Kiosk config group lives on the location: each hotel belongs to one
    // group (imported from Monday column 1466686598). Nullable FK + ON DELETE
    // SET NULL so removing a group does not cascade-delete locations.
    kioskConfigGroupId: uuid("kiosk_config_group_id").references(
      () => kioskConfigGroups.id,
      { onDelete: "set null" },
    ),
    customFields: jsonb("custom_fields").$type<Record<string, string>>(),
    // Phase 1 M1 Task 1.5 — hotel dimension fields (ported from data-dashboard analytics schema)
    numRooms: integer("num_rooms"),
    hotelAddress: text("hotel_address"),
    liveDate: timestamp("live_date"),
    launchPhase: text("launch_phase"),
    keyContactName: text("key_contact_name"),
    keyContactEmail: text("key_contact_email"),
    financeContact: text("finance_contact"),
    // D6 / Task 2.12 — IANA zone (e.g. 'Europe/London') used by hour-of-day
    // analytics to bucket sales by local time. NOT NULL so SQL never falls
    // back to UTC silently; backfilled per-region in migration 0033 and
    // editable on the location detail form. Default 'UTC' is safe (matches
    // pre-D6 naïve behaviour) for any row that escapes the backfill.
    ianaTimezone: text("iana_timezone").notNull().default("UTC"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    // Phase 9 — POC alert silencing now lives at the location (hotel) level.
    // When set, the weekly alert job skips every kiosk at this location.
    // Reason is a free-text note for the admin UI ("hotel asked for 4-week
    // reprieve", etc.). Migrated from kiosks in 0045.
    alertSilencedAt: timestamp("alert_silenced_at", { withTimezone: true }),
    alertSilencedReason: text("alert_silenced_reason"),
  },
  (t) => ({
    // Phase 7 Plan 07-04 (DATA-03) — partial unique index over the canonical
    // normalised name, scoped to active rows. Two active rows with the same
    // normalised name fail at INSERT/UPDATE; archived rows (and the sentinel,
    // whose normalised name is "locationneeded" — explicitly excluded by the
    // detection helper, not by the index) can coexist freely. Backfilled in
    // Task 1 Step 1 before this index lands so the CREATE INDEX never fails
    // on legacy data.
    normalisedNameUniqueActive: uniqueIndex(
      "locations_normalised_name_unique_active",
    )
      .on(t.normalisedName)
      .where(sql`archived_at IS NULL`),
    // Phase 7 Plan 07-06 — partial unique on (region, customer_code) WHERE
    // NOT NULL. Replaces the dropped (region, outlet_code) compound; allows
    // multiple-NULL rows (placeholders) per region.
    customerCodePerRegionUniq: uniqueIndex(
      "locations_region_customer_code_partial_uniq",
    )
      .on(t.primaryRegionId, t.customerCode)
      .where(sql`customer_code IS NOT NULL`),
    // Phase 7 Plan 07-06 — partial unique on monday_item_id (the importer's
    // ON CONFLICT target). Partial so legacy rows inserted before the column
    // existed (NULL monday_item_id) don't conflict.
    mondayItemIdPartialUniq: uniqueIndex(
      "locations_monday_item_id_partial_uniq",
    )
      .on(t.mondayItemId)
      .where(sql`monday_item_id IS NOT NULL`),
  }),
);

// Kiosk assignments — temporal join table for assignment history
export const kioskAssignments = pgTable(
  "kiosk_assignments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kioskId: uuid("kiosk_id")
      .notNull()
      .references(() => kiosks.id),
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id),
    assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
    unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
    reason: text("reason"),
    assignedBy: text("assigned_by").notNull(),
    assignedByName: text("assigned_by_name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byLocAssigned: index("kiosk_assignments_loc_assigned_idx").on(t.locationId, t.assignedAt),
  }),
);

// Audit log — append-only with denormalized actor/entity names
export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  actorId: text("actor_id"),
  actorName: text("actor_name"),
  entityType: text("entity_type").notNull(),
  // text (not uuid) — entity IDs are heterogeneous across types: kiosks /
  // installations / locations are uuid, but Better Auth user IDs are random
  // 32-char strings. uuid would reject the user-typed audit rows.
  entityId: text("entity_id").notNull(),
  entityName: text("entity_name"),
  action: text("action").notNull(),
  field: text("field"),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// Phase 7 Plan 07-03 — N→1 location-merge snapshot-before-commit (D-03 / DATA-02).
// Each row captures the pre-merge FK state for a single forward-merge transaction.
// Linked 1:1 to the merge audit-log entry via auditLogId. The undo server action
// (src/app/(app)/admin/audit-log/[id]/actions/undo-merge.ts) replays the payload
// to reverse FK migrations and restore archived rows; the snapshot row is
// DELETEd on successful undo (the row's existence is the single source of truth
// for "undo still available").
export const locationMergeSnapshots = pgTable("location_merge_snapshots", {
  id: uuid("id").primaryKey().defaultRandom(),
  auditLogId: uuid("audit_log_id")
    .notNull()
    .references(() => auditLogs.id),
  payload: jsonb("payload").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

// User views — saved filter/sort/group configurations
export const userViews = pgTable("user_views", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  name: text("name").notNull(),
  entityType: text("entity_type").notNull(),
  viewType: text("view_type").notNull().default("table"),
  config: jsonb("config")
    .$type<{
      filters?: Record<string, unknown>;
      sort?: Record<string, unknown>;
      groupBy?: string;
      columns?: string[];
    }>()
    .notNull(),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// =============================================================================
// Phase 3 — Installation tables
// =============================================================================

// Installations — project-level grouping of kiosks with date range and status
export const installations = pgTable("installations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  region: text("region"),
  status: text("status").notNull().default("planned"),
  plannedStart: timestamp("planned_start", { withTimezone: true }),
  plannedEnd: timestamp("planned_end", { withTimezone: true }),
  // Internal POC / assignee — the user responsible for this installation.
  // Nullable; ON DELETE SET NULL in the migration.
  internalPocId: text("internal_poc_id").references(() => user.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Milestones — key dates on an installation (contract signing, go-live, etc.)
export const milestones = pgTable("milestones", {
  id: uuid("id").primaryKey().defaultRandom(),
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  targetDate: timestamp("target_date", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// installationKiosks — join table linking installations to kiosks
export const installationKiosks = pgTable("installation_kiosks", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  kioskId: uuid("kiosk_id")
    .notNull()
    .references(() => kiosks.id, { onDelete: "cascade" }),
}, (t) => [primaryKey({ columns: [t.installationId, t.kioskId] })]);

// installationMembers — join table for team members on an installation
export const installationMembers = pgTable("installation_members", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").notNull(),
}, (t) => [primaryKey({ columns: [t.installationId, t.userId] })]);

// =============================================================================
// Phase 4 — Product/Provider tables
// =============================================================================

// Products — distinct product types (e.g. Transfers, Tours & Activities).
// NetSuite ETL (2026-04-24): dimension resolver prefers `netsuiteCode` match
// over `name`; `categoryCode`/`categoryName` denormalised from NetSuite for
// downstream reporting (populated on insert / updated when null).
export const products = pgTable("products", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  netsuiteCode: text("netsuite_code").unique(),
  categoryCode: text("category_code"),
  categoryName: text("category_name"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Providers — companies providing products (e.g. Uber, TUI Musement)
export const providers = pgTable("providers", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Location products — per-hotel product availability, provider assignment, and commission tiers
export const locationProducts = pgTable("location_products", {
  id: uuid("id").primaryKey().defaultRandom(),
  locationId: uuid("location_id").notNull().references(() => locations.id),
  productId: uuid("product_id").notNull().references(() => products.id),
  providerId: uuid("provider_id").references(() => providers.id),
  availability: text("availability").notNull().default("unavailable"),
  commissionTiers: jsonb("commission_tiers").$type<Array<{
    effectiveFrom: string;
    tiers: Array<{ minRevenue: number; maxRevenue: number | null; rate: number }>;
  }>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Commission ledger — per-sale commission calculation records with tier breakdown
export const commissionLedger = pgTable(
  "commission_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    salesRecordId: uuid("sales_record_id")
      .notNull()
      .references(() => salesRecords.id, { onDelete: "cascade" }),
    locationProductId: uuid("location_product_id")
      .references(() => locationProducts.id, { onDelete: "set null" }),
    // Phase 9.1 / PR #40 review (observation A) — renamed from `gross_amount`
    // to make the GBP-normalised semantics explicit. FX-04 stores the GBP
    // commission base here (D-15), and the dashboard "Total Commission" /
    // "Commissionable Revenue" tiles read from this column directly without
    // an FX round-trip. See migration 0049.
    grossAmountGbp: numeric("gross_amount_gbp", { precision: 12, scale: 2 }).notNull(),
    commissionableAmount: numeric("commissionable_amount", { precision: 12, scale: 2 }).notNull(),
    commissionAmount: numeric("commission_amount", { precision: 12, scale: 2 }).notNull(),
    tierBreakdown: jsonb("tier_breakdown")
      .$type<Array<{ tierRate: number; revenueInTier: number; commission: number }>>()
      .notNull(),
    tierVersionEffectiveFrom: text("tier_version_effective_from").notNull(),
    calculatedAt: timestamp("calculated_at", { withTimezone: true }).defaultNow().notNull(),
    isReversal: boolean("is_reversal").notNull().default(false),
  },
  (t) => ({
    bySalesRecord: index("cl_sales_record_idx").on(t.salesRecordId),
    byLocationProductReversal: index("cl_location_product_idx").on(t.locationProductId, t.isReversal),
  }),
);

// Phase 4.1 note: appSettings already declared above (line ~88).

// Duplicate dismissals — admin marks a pair of locations as "not duplicates";
// stored canonical-ordered (locationAId < locationBId lexicographically) so
// the UNIQUE constraint collapses both directions of the pair.
export const duplicateDismissals = pgTable(
  "duplicate_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    locationAId: uuid("location_a_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    locationBId: uuid("location_b_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    dismissedBy: text("dismissed_by").notNull(),
    dismissedByName: text("dismissed_by_name").notNull(),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    uniqueIndex("duplicate_dismissals_pair_idx").on(t.locationAId, t.locationBId),
  ]
);

// =============================================================================
// Phase 1 — User scopes (dimension-based access scoping)
// =============================================================================

// INVARIANT: users with userType='external' MUST have >=1 row in userScopes.
// Enforced in invite-accept handler (src/lib/auth/invite.ts) and in scopedQuery().
// Not enforced at DB layer because insert-ordering makes a CHECK constraint impractical.
export const userScopes = pgTable(
  "user_scopes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    roleId: uuid("role_id").references(() => roles.id, { onDelete: "cascade" }),
    dimensionType: text("dimension_type", {
      enum: [
        "hotel_group",
        "location",
        "region",
        "product",
        "provider",
        "location_group",
      ],
    }).notNull(),
    dimensionId: text("dimension_id").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    createdBy: text("created_by").references(() => user.id),
  },
  (t) => ({
    uniq: unique().on(t.userId, t.roleId, t.dimensionType, t.dimensionId),
    byUser: index("user_scopes_user_idx").on(t.userId),
  })
);

// =============================================================================
// Phase 1 M1 Task 1.6 — Analytics dimension tables
// Ported from data-dashboard. These enable scoped analytics: a user with
// userScopes.dimensionType='hotel_group' sees only locations belonging to that
// hotel_group via the membership join tables below.
//
// NOTE: free-text columns `locations.hotel_group` and `locations.location_group`
// coexist with these dimension tables — the tables are used for scoped joins
// while the free-text columns remain for legacy input / unnormalised data.
// The previously free-text region column on `locations` was dropped in
// migration 0018 in favour of joining via the region dimension tables below.
// =============================================================================

// Markets — top-level geographic grouping (e.g. UK & Ireland, Continental Europe).
// Regions belong to a market, enabling hierarchical geo drill-down.
export const markets = pgTable("markets", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  code: text("code"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Hotel groups — hierarchical grouping of hotel locations (e.g. Dalata Hotels).
// Supports nesting via self-referential parentGroupId.
// `archivedAt` (D5 PR-6 Part C, migration 0031) marks comma-encoded JV rows
// that were rewritten into proper multi-memberships and should no longer
// appear in selectors / filters.
export const hotelGroups = pgTable("hotel_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  parentGroupId: uuid("parent_group_id").references(
    (): AnyPgColumn => hotelGroups.id,
    { onDelete: "set null" },
  ),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Regions — geographic grouping of locations (e.g. UK, EU, North America).
// `code` is the canonical WKG region identifier (UK, IE, DE, ES, CZ). `azureCode`
// is the (configurable) prefix used for Azure blob paths (e.g. UK→GB). See
// docs/plans/2026-04-24-netsuite-etl-restructure-design.md §Data model.
export const regions = pgTable("regions", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  code: text("code").notNull().unique(),
  azureCode: text("azure_code").unique(),
  marketId: uuid("market_id").references(() => markets.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Location groups — arbitrary groupings for scoped access (e.g. "City Centre Hotels").
export const locationGroups = pgTable("location_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  description: text("description"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id),
});

// Membership join tables (many-to-many between locations and dimensions).
// Composite PK on (locationId, dimensionId) prevents duplicates.
// Cascade delete from both sides keeps memberships in sync.

export const locationHotelGroupMemberships = pgTable(
  "location_hotel_group_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    hotelGroupId: uuid("hotel_group_id")
      .notNull()
      .references(() => hotelGroups.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.hotelGroupId] }),
    byHotelGroup: index("lhg_hotel_group_idx").on(t.hotelGroupId),
  }),
);

export const locationRegionMemberships = pgTable(
  "location_region_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    regionId: uuid("region_id")
      .notNull()
      .references(() => regions.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.regionId] }),
    byRegion: index("lrm_region_idx").on(t.regionId),
    // 1-per-location invariant per Resolved Decision D5 (migration 0029).
    // Composite PK above blocks (loc,region) duplicates; this UNIQUE blocks a
    // location from belonging to two different regions at once.
    locationUniq: unique("location_region_memberships_location_id_unique").on(
      t.locationId,
    ),
  }),
);

export const locationGroupMemberships = pgTable(
  "location_group_memberships",
  {
    locationId: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "cascade" }),
    locationGroupId: uuid("location_group_id")
      .notNull()
      .references(() => locationGroups.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.locationId, t.locationGroupId] }),
    byLocationGroup: index("lgm_location_group_idx").on(t.locationGroupId),
    // 1-per-location invariant per Resolved Decision D5 (migration 0030).
    // Composite PK above blocks (loc,group) duplicates; this UNIQUE blocks a
    // location from belonging to two different location groups at once.
    locationUniq: unique("location_group_memberships_location_id_unique").on(
      t.locationId,
    ),
  }),
);

// =============================================================================
// Phase 1 M1 Task 1.7 — Sales-data pipeline tables
// Ported from data-dashboard CSV shape. Three tables:
//   - salesImports    — one row per CSV upload (metadata + status)
//   - importStagings  — per-row staging area pre-commit (validation/rollback)
//   - salesRecords    — committed fact table (per transaction)
//
// Ordering note: salesImports declared FIRST (no forward FKs); importStagings
// next (references salesImports); salesRecords last (references salesImports).
// Only salesRecords.importId points AT salesImports — not reverse — so no
// circular dependency at declaration time.
//
// NOTE: drizzle-kit's `text(..., { enum: [...] })` helper enforces the enum
// at the TypeScript type level only. The migration (0008) hand-appends CHECK
// constraints at the DB layer for `sales_imports.status` and
// `import_stagings.status`, matching the pattern established by 0003 and 0005.
// =============================================================================

export const salesImports = pgTable("sales_imports", {
  id: uuid("id").primaryKey().defaultRandom(),
  filename: text("filename").notNull(),
  // Unique so duplicate uploads are caught at the DB layer (not just app-level).
  sourceHash: text("source_hash").notNull().unique(),
  uploadedBy: text("uploaded_by").notNull().references(() => user.id),
  uploadedAt: timestamp("uploaded_at").notNull().defaultNow(),
  rowCount: integer("row_count").notNull().default(0),
  dateRangeStart: date("date_range_start"),
  dateRangeEnd: date("date_range_end"),
  status: text("status", { enum: ["staging", "committed", "failed", "rolled_back"] })
    .notNull()
    .default("staging"),
  errors: jsonb("errors"),
  // NetSuite ETL (2026-04-24): an import is always region-scoped. Set at stage
  // time; downstream salesRecords.regionId is propagated from this value.
  regionId: uuid("region_id").references(() => regions.id),
});

export const importStagings = pgTable(
  "import_stagings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id")
      .notNull()
      .references(() => salesImports.id, { onDelete: "cascade" }),
    rowNumber: integer("row_number").notNull(),
    rawRow: jsonb("raw_row").notNull(),
    parsedRow: jsonb("parsed_row"),
    status: text("status", { enum: ["pending", "valid", "invalid", "committed"] })
      .notNull()
      .default("pending"),
    validationErrors: jsonb("validation_errors"),
  },
  (t) => ({
    byImport: index("staging_import_idx").on(t.importId),
  }),
);

// NetSuite ETL (2026-04-24): sales_records rewritten around net/VAT measures.
// Dropped fields: grossAmount, quantity, discountCode, discountAmount,
// bookingFee, saleCommission, unique(saleRef, transactionDate). Row identity
// is now guaranteed by blob-level idempotency (sales_blob_ingestions) + the
// feed's "no overlap between days" guarantee; reversal pairs legitimately
// share (saleRef, refNo, transactionDate) with opposite-signed amounts.
//
// Reversal columns (D2, migration 0027): isReversal / isPartialReversal /
// originalRecordId / processedAtLocationId. Populated at CSV ingest by
// matching (refNo, opposite sign, equal magnitude). For matched refunds the
// row's locationId is rewritten to the original's locationId so cancellations
// attribute to the booking outlet, and processedAtLocationId retains the CSV
// attribution. Unmatched ("orphan") refunds keep the CSV's location_id and
// originalRecordId stays NULL.
export const salesRecords = pgTable(
  "sales_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id").references(() => salesImports.id, { onDelete: "set null" }),
    // no onDelete — regions are never deleted while sales exist; block the delete rather than cascading.
    regionId: uuid("region_id")
      .notNull()
      .references(() => regions.id),
    saleRef: text("sale_ref").notNull(),
    refNo: text("ref_no").notNull(),
    transactionDate: date("transaction_date").notNull(),
    transactionTime: time("transaction_time"),
    locationId: uuid("location_id").notNull().references(() => locations.id),
    productId: uuid("product_id").notNull().references(() => products.id),
    providerId: uuid("provider_id").references(() => providers.id),
    netAmount: numeric("net_amount", { precision: 12, scale: 2 }).notNull(),
    netAmountGbp: numeric("net_amount_gbp", { precision: 12, scale: 2 }), // Phase 9.1 plan 09.1-02 — nullable until 0048 NOT NULL flip in plan 09.1-05
    vatAmount: numeric("vat_amount", { precision: 12, scale: 2 }).notNull(),
    vatRate: numeric("vat_rate", { precision: 5, scale: 2 }),
    currency: text("currency").notNull().default("GBP"),
    isWeknowFee: boolean("is_weknow_fee").notNull().default(false),
    netsuiteCode: text("netsuite_code").notNull(),
    agent: text("agent"),
    businessDivision: text("business_division"),
    categoryCode: text("category_code"),
    categoryName: text("category_name"),
    apiProductName: text("api_product_name"),
    city: text("city"),
    country: text("country"),
    customerCode: text("customer_code"),
    customerName: text("customer_name"),
    isReversal: boolean("is_reversal").notNull().default(false),
    isPartialReversal: boolean("is_partial_reversal").notNull().default(false),
    originalRecordId: uuid("original_record_id").references((): AnyPgColumn => salesRecords.id, {
      onDelete: "set null",
    }),
    processedAtLocationId: uuid("processed_at_location_id").references(() => locations.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => ({
    regionDateIdx: index("sales_region_date_idx").on(t.regionId, t.transactionDate),
    regionRefNoIdx: index("sales_region_refno_idx").on(t.regionId, t.refNo),
    regionSaleRefIdx: index("sales_region_saleref_idx").on(t.regionId, t.saleRef),
    locDateIdx: index("sales_loc_date_idx").on(t.locationId, t.transactionDate),
    prodDateIdx: index("sales_prod_date_idx").on(t.productId, t.transactionDate),
    provDateIdx: index("sales_prov_date_idx").on(t.providerId, t.transactionDate),
    txnDateIdx: index("sales_txn_date_idx").on(t.transactionDate),
    isReversalIdx: index("sales_records_is_reversal_idx").on(t.isReversal),
    originalRecordIdx: index("sales_records_original_record_id_idx").on(t.originalRecordId),
    // No natural unique — idempotency enforced at blob level.
  }),
);

// NetSuite ETL (2026-04-24): audit trail + idempotency for Azure blob ingestions.
// One row per blob processed (success or failure). The (regionId, blobPath)
// unique constraint is the idempotency key — the ETL runner skips any blob
// already present with status='success'. Failures are re-processed on retry
// via onConflictDoUpdate.
export const salesBlobIngestions = pgTable(
  "sales_blob_ingestions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // no onDelete — regions are never deleted while sales exist; block the delete rather than cascading.
    regionId: uuid("region_id")
      .notNull()
      .references(() => regions.id),
    blobPath: text("blob_path").notNull(),
    blobDate: date("blob_date").notNull(),
    etag: text("etag"),
    processedAt: timestamp("processed_at").notNull().defaultNow(),
    importId: uuid("import_id").references(() => salesImports.id, { onDelete: "set null" }),
    status: text("status", { enum: ["success", "failed"] }).notNull(),
    errorMessage: text("error_message"),
  },
  (t) => ({
    regionBlobUniq: unique("sales_blob_ingestions_region_blob_unique").on(
      t.regionId,
      t.blobPath,
    ),
    byRegionDate: index("sales_blob_ingestions_region_date_idx").on(
      t.regionId,
      t.blobDate,
    ),
  }),
);

// NetSuite ETL (2026-04-24): admin-editable map from a NetSuite Product Name
// to the NetSuite code used when the CSV `Code` column is NULL (happens for
// Booking Fee / Cash Handling Fee rows today). Edits MUST go through
// src/lib/sales/config/fee-fallbacks.ts#updateFeeCodeFallback so denormalised
// codes on products + sales_records are backfilled in the same transaction.
export const productCodeFallbacks = pgTable("product_code_fallbacks", {
  id: uuid("id").primaryKey().defaultRandom(),
  productName: text("product_name").notNull().unique(),
  netsuiteCode: text("netsuite_code").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// =============================================================================
// Phase 1 M1 Task 1.8 — Remaining analytics tables (ported from data-dashboard)
//
// Source migrations in /Users/vedant/Work/WeKnowGroup/data-dashboard/supabase/migrations/:
//   - 20260223_add_outlet_exclusions.sql          → outletExclusions
//   - 20260317_phase4_trend_builder.sql           → eventCategories, businessEvents,
//                                                   analyticsSavedViews (saved_views),
//                                                   weatherCache
// Inferred (no Supabase migration — see task 1.8 in docs/plans):
//   - analyticsPresets — saved filter/dimension configs (shape per design doc).
//   - eventLog         — lightweight analytics usage tracking.
//
// Adaptations vs Supabase source:
//   - `auth.users(id) uuid` → `user.id text` (Better Auth text IDs).
//   - Dropped Supabase RLS policies / is_admin() / auth.uid() references;
//     scoping is handled in our scopedQuery() layer.
//   - `saved_views.series_config` (jsonb) → `analyticsSavedViews.config` +
//     added `viewType` (trend|pivot|heatmap) enum per design doc.
//   - CHECK constraints for text({enum}) columns are hand-appended in the
//     0009 migration (same pattern as 0003/0005/0008).
// =============================================================================

// outletExclusions — admin-managed outlet exclusion rules with exact/regex patterns.
// Per Task 1.9 (PR-6 Part F) exclusions are scoped to a single region: outlet
// codes are unique per (region_id, outlet_code) but not globally, so an
// exclusion that targets one region's 'Q5' must not silently apply to AU/DE/ES.
export const outletExclusions = pgTable(
  "outlet_exclusions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    outletCode: text("outlet_code").notNull(),
    patternType: text("pattern_type", { enum: ["exact", "regex"] })
      .notNull()
      .default("exact"),
    label: text("label"),
    regionId: uuid("region_id")
      .notNull()
      .references(() => regions.id, { onDelete: "restrict" }),
    createdBy: text("created_by").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    uniq: unique().on(t.outletCode, t.patternType, t.regionId),
    byPatternType: index("outlet_exclusions_pattern_type_idx").on(t.patternType),
    byOutletCode: index("outlet_exclusions_outlet_code_idx").on(t.outletCode),
  }),
);

// analyticsPresets — saved filter/dimension configs (per-user, shareable).
// Inferred shape — no Supabase migration; see M1 Task 1.8 notes.
export const analyticsPresets = pgTable("analytics_presets", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  ownerId: text("owner_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  config: jsonb("config").notNull(),
  isShared: boolean("is_shared").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// analyticsSavedViews — per-user saved analytics view configurations
// (trend / pivot / heatmap). Ported from data-dashboard `saved_views` with
// `viewType` added per our design doc; Supabase `series_config` → `config`.
export const analyticsSavedViews = pgTable(
  "analytics_saved_views",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    viewType: text("view_type", { enum: ["trend", "pivot", "heatmap"] }).notNull(),
    config: jsonb("config").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    uniqOwnerName: unique().on(t.ownerId, t.name),
    byOwner: index("analytics_saved_views_owner_idx").on(t.ownerId),
  }),
);

// eventCategories — taxonomy for business events (Promotion, Holiday, ...).
export const eventCategories = pgTable("event_categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  color: text("color").notNull().default("#666666"),
  isCore: boolean("is_core").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// businessEvents — annotatable business events shown on trend charts.
export const businessEvents = pgTable(
  "business_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    title: text("title").notNull(),
    description: text("description"),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => eventCategories.id),
    startDate: date("start_date").notNull(),
    endDate: date("end_date"),
    scopeType: text("scope_type", {
      enum: ["global", "hotel", "region", "hotel_group"],
    }),
    scopeValue: text("scope_value"),
    createdBy: text("created_by").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byDates: index("business_events_dates_idx").on(t.startDate, t.endDate),
  }),
);

// weatherCache — cache of weather API responses keyed by cacheKey (e.g.
// "loc:<locationId>:<date>"). Supabase source uses a single text PK cache_key
// which already gives us the composite-uniqueness property (locationId+date).
export const weatherCache = pgTable(
  "weather_cache",
  {
    cacheKey: text("cache_key").primaryKey(),
    dateFrom: date("date_from").notNull(),
    dateTo: date("date_to").notNull(),
    data: jsonb("data").notNull(),
    isForecast: boolean("is_forecast").notNull().default(false),
    cachedAt: timestamp("cached_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byCachedAt: index("weather_cache_cached_idx").on(t.cachedAt),
  }),
);

// =============================================================================
// Phase 1 M11.2 — Location performance flags
// Allows admins to flag underperforming locations for triage (relocate, monitor,
// or strategic_exception). Flags remain active until explicitly resolved.
// =============================================================================

export const locationFlags = pgTable("location_flags", {
  id: uuid("id").primaryKey().defaultRandom(),
  locationId: uuid("location_id")
    .notNull()
    .references(() => locations.id, { onDelete: "cascade" }),
  flagType: text("flag_type", { enum: ["relocate", "monitor", "strategic_exception"] }).notNull(),
  reason: text("reason"),
  actorId: text("actor_id")
    .notNull()
    .references(() => user.id),
  actorName: text("actor_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  resolvedBy: text("resolved_by").references(() => user.id),
  resolutionNote: text("resolution_note"),
});

// =============================================================================
// Phase 1 M12.2 — Experiment cohorts
// Allows users to define location cohorts, compare metrics against a control
// group (rest of portfolio or named locations), and overlay intervention dates.
// =============================================================================

// Per-user uniqueness on (created_by, name): two users may both have a "Q1
// Promo" cohort, but a single user cannot have two with the same name. The
// list view already filters by createdBy for non-admins, so per-user scope
// matches the visible namespace.
export const experimentCohorts = pgTable(
  "experiment_cohorts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    description: text("description"),
    locationIds: jsonb("location_ids").$type<string[]>().notNull(),
    controlType: text("control_type", { enum: ["rest_of_portfolio", "named_control"] }).notNull().default("rest_of_portfolio"),
    controlLocationIds: jsonb("control_location_ids").$type<string[]>(),
    interventionDate: date("intervention_date"),
    createdBy: text("created_by").notNull().references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("experiment_cohorts_created_by_name_unique").on(t.createdBy, t.name),
  ],
);

// =============================================================================
// Phase 1 M13.2 — Insight-to-action workflow
// Action items derived from performance flags, data-quality issues, or manual
// creation. Tracks investigation, relocation, training, and equipment changes.
// =============================================================================

export const actionItems = pgTable("action_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  sourceType: text("source_type", { enum: ["flag", "manual", "data_quality"] }).notNull(),
  sourceId: text("source_id"),
  locationId: uuid("location_id").references(() => locations.id, { onDelete: "set null" }),
  actionType: text("action_type", { enum: ["investigation", "relocation", "training", "equipment_change"] }).notNull(),
  title: text("title").notNull(),
  description: text("description"),
  ownerId: text("owner_id").references(() => user.id, { onDelete: "set null" }),
  dueDate: date("due_date"),
  status: text("status", { enum: ["open", "in_progress", "resolved", "cancelled"] }).notNull().default("open"),
  outcomeNotes: text("outcome_notes"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdBy: text("created_by").notNull().references(() => user.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// =============================================================================
// Phase 6 Plan 06-01 — D8 multi-POS merge proposals
//
// Persists per-cluster admin decisions made via the
// /settings/duplicates/merge-review UI. Source CSV at
// `tasks/analytics-audit/multi-pos-merge-proposal.csv` enumerates the 22
// clusters; admin walks through each and saves a decision row here keyed on
// (canonical_id, defunct_id). The bulk-merge primitive (src/lib/multi-pos-merge.ts)
// reads `decision IN ('approved','swapped')` rows where `applied_at IS NULL`
// and rewrites every FK to `locations.id` from defunct → canonical, then
// stamps `applied_at`. `decision='address_fix'` rows are surfaced for manual
// data-quality fixes (Phase 5.7 ride-along) and do NOT trigger a merge.
// =============================================================================

export const mergeProposals = pgTable(
  "merge_proposals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clusterId: integer("cluster_id").notNull(),
    canonicalId: uuid("canonical_id")
      .notNull()
      .references(() => locations.id),
    defunctId: uuid("defunct_id")
      .notNull()
      .references(() => locations.id),
    // CHECK constraint enforced at DB layer in migration 0038 — Drizzle's
    // `text({ enum: [...] })` only types the value at the TS layer.
    decision: text("decision", {
      enum: ["approved", "swapped", "rejected", "address_fix"],
    }).notNull(),
    notes: text("notes"),
    decidedBy: text("decided_by").notNull(),
    decidedByName: text("decided_by_name").notNull(),
    decidedAt: timestamp("decided_at", { withTimezone: true }).defaultNow().notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }),
  },
  (t) => ({
    pairUniq: unique("merge_proposals_pair_unique").on(t.canonicalId, t.defunctId),
    byCluster: index("merge_proposals_cluster_idx").on(t.clusterId),
    byApplied: index("merge_proposals_applied_idx").on(t.appliedAt),
  }),
);

// eventLog — lightweight analytics usage tracking. userId is nullable to
// support anonymous / system events (e.g. scheduled exports).
export const eventLog = pgTable(
  "event_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
    actionType: text("action_type").notNull(),
    metadata: jsonb("metadata"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byUser: index("event_log_user_idx").on(t.userId),
    byAction: index("event_log_action_idx").on(t.actionType),
    byOccurred: index("event_log_occurred_idx").on(t.occurredAt),
  }),
);

// Phase 8 Plan 08-01 — email_log audit table (EMAIL-04, D-06).
// One row per send, regardless of transport (sync Resend OR Inngest async).
// Partial unique idx on (kind, payload_hash) WHERE payload_hash IS NOT NULL
// enforces digest idempotency at the DB; auth-flow sends pass payload_hash=NULL
// so they never collide.
export const emailLog = pgTable(
  "email_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: text("kind").notNull(),
    recipient: text("recipient").notNull(),
    resendMessageId: text("resend_message_id"),
    inngestRunId: text("inngest_run_id"),
    status: text("status", { enum: ["queued", "sent", "failed", "skipped"] }).notNull(),
    lastError: text("last_error"),
    payloadHash: text("payload_hash"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    kindPayloadHashUq: uniqueIndex("email_log_kind_payload_hash_uq")
      .on(t.kind, t.payloadHash)
      .where(sql`payload_hash IS NOT NULL`),
    recipientCreatedAtIdx: index("email_log_recipient_created_at_idx").on(
      t.recipient,
      t.createdAt.desc(),
    ),
  }),
);

// Phase 9 — POC underperformance alert state (POC-ALERT-01).
// One row per LOCATION (hotel) — upserted each time the weekly Inngest job
// runs. Tracks the current composite-score tier classification (used to
// detect transitions into "Emerging") and when the last alert email was
// sent (used to enforce the 30-day re-alert window). Composite score is
// recorded numerically so the audit-log reader can show drift without
// re-running the classifier.
export const locationPerformanceAlertState = pgTable(
  "location_performance_alert_state",
  {
    locationId: uuid("location_id")
      .primaryKey()
      .references(() => locations.id, { onDelete: "cascade" }),
    tier: text("tier", {
      enum: ["Premium", "Standard", "Developing", "Emerging"],
    }).notNull(),
    compositeScore: numeric("composite_score", { precision: 6, scale: 2 }).notNull(),
    classifiedAt: timestamp("classified_at", { withTimezone: true }).notNull(),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }).notNull(),
    lastAlertedAt: timestamp("last_alerted_at", { withTimezone: true }),
  },
  (t) => ({
    tierIdx: index("location_performance_alert_state_tier_idx").on(t.tier),
  }),
);

// Phase 9.1 plan 09.1-02 — Multi-currency analytics, FX-01.
// Daily Bank of England spot rates per currency. PK on (currency, rate_date)
// so the daily Inngest cron can ON CONFLICT DO NOTHING idempotently. rate_to_gbp
// uses numeric(18,10) to retain JPY-class precision (BoE publishes XUDLJYS at
// ~6 decimals; 10 is future-headroom for KRW/IDR-style very-low-value
// currencies). source defaults 'boe' so a future NetSuite-as-source phase can
// coexist without a schema change.
export const exchangeRates = pgTable(
  "exchange_rates",
  {
    currency: text("currency").notNull(),
    rateDate: date("rate_date").notNull(),
    rateToGbp: numeric("rate_to_gbp", { precision: 18, scale: 10 }).notNull(),
    source: text("source").notNull().default("boe"),
    fetchedAt: timestamp("fetched_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.currency, t.rateDate] }),
  }),
);

// =============================================================================
// Phase 10 — RBAC: roles, role_permissions, user_roles
// =============================================================================

export const roles = pgTable("roles", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  kind: text("kind", { enum: ["system", "tier", "custom"] }).notNull(),
  displayName: text("display_name").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const rolePermissions = pgTable(
  "role_permissions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roleId: uuid("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    action: text("action").notNull(),
    subject: text("subject").notNull(),
    fields: jsonb("fields").$type<string[] | null>(),
    conditions: jsonb("conditions").$type<Record<string, unknown> | null>(),
    inverted: boolean("inverted").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    byRole: index("role_permissions_role_idx").on(t.roleId),
  }),
);

export const userRoles = pgTable(
  "user_roles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    roleId: uuid("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
    assignedBy: text("assigned_by").references(() => user.id),
  },
  (t) => ({
    uniq: unique().on(t.userId, t.roleId),
    byUser: index("user_roles_user_idx").on(t.userId),
  }),
);
