import {
  pgTable,
  text,
  timestamp,
  boolean,
  doublePrecision,
  uuid,
  integer,
  jsonb,
  numeric,
  primaryKey,
  uniqueIndex,
  unique,
  index,
} from "drizzle-orm/pg-core";

// =============================================================================
// Better Auth tables
// These match the schema generated by Better Auth 1.5 with the admin plugin.
// Do NOT modify column names — Better Auth expects these exact names.
// =============================================================================

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  // Admin plugin columns
  role: text("role").default("member"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  // Phase 1 — user classification (internal staff vs external hotel users)
  userType: text("user_type", { enum: ["internal", "external"] })
    .notNull()
    .default("internal"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// =============================================================================
// Application tables
// =============================================================================

// Phase 4.1 — Kiosk Config Groups (defined before kiosks for FK reference)
export const kioskConfigGroups = pgTable("kiosk_config_groups", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// App settings key-value store (board ID persistence, per D-13)
export const appSettings = pgTable("app_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Pipeline stages — FLOAT8 for position to avoid batch-update race conditions
export const pipelineStages = pgTable("pipeline_stages", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  position: doublePrecision("position").notNull(),
  color: text("color"),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Kiosks
export const kiosks = pgTable("kiosks", {
  id: uuid("id").primaryKey().defaultRandom(),
  kioskId: text("kiosk_id").notNull().unique(),
  outletCode: text("outlet_code"),
  hardwareModel: text("hardware_model"),
  hardwareSerialNumber: text("hardware_serial_number"),
  softwareVersion: text("software_version"),
  cmsConfigStatus: text("cms_config_status"),
  installationDate: timestamp("installation_date"),
  deploymentPhaseTags: jsonb("deployment_phase_tags").$type<string[]>(),
  maintenanceFee: numeric("maintenance_fee"),
  freeTrialStatus: boolean("free_trial_status").default(false),
  freeTrialEndDate: timestamp("free_trial_end_date"),
  regionGroup: text("region_group"),
  pipelineStageId: uuid("pipeline_stage_id").references(() => pipelineStages.id),
  kioskConfigGroupId: uuid("kiosk_config_group_id").references(() => kioskConfigGroups.id),
  notes: text("notes"),
  customFields: jsonb("custom_fields").$type<Record<string, string>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
});

// Locations
export const locations = pgTable("locations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  address: text("address"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  starRating: integer("star_rating"),
  roomCount: integer("room_count"),
  keyContacts: jsonb("key_contacts").$type<
    Array<{ name: string; role: string; email: string; phone: string }>
  >(),
  customerCode: text("customer_code"),
  hotelGroup: text("hotel_group"),
  sourcedBy: text("sourced_by"),
  bankingDetails: jsonb("banking_details"),
  contractValue: numeric("contract_value"),
  contractStartDate: timestamp("contract_start_date"),
  contractEndDate: timestamp("contract_end_date"),
  contractTerms: text("contract_terms"),
  contractDocuments: jsonb("contract_documents").$type<
    Array<{ fileName: string; s3Key: string; uploadedAt: string }>
  >(),
  maintenanceFee: numeric("maintenance_fee"),
  freeTrialEndDate: timestamp("free_trial_end_date"),
  hardwareAssets: text("hardware_assets"),
  notes: text("notes"),
  // Phase 4.1 — new location fields (D-22)
  region: text("region"),
  locationGroup: text("location_group"),
  internalPocId: text("internal_poc_id").references(() => user.id),
  status: text("status"),
  customFields: jsonb("custom_fields").$type<Record<string, string>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
});

// Kiosk assignments — temporal join table for assignment history
export const kioskAssignments = pgTable("kiosk_assignments", {
  id: uuid("id").primaryKey().defaultRandom(),
  kioskId: uuid("kiosk_id")
    .notNull()
    .references(() => kiosks.id),
  locationId: uuid("location_id")
    .notNull()
    .references(() => locations.id),
  assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
  unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
  reason: text("reason"),
  assignedBy: text("assigned_by").notNull(),
  assignedByName: text("assigned_by_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// Audit log — append-only with denormalized actor/entity names
export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  actorId: text("actor_id"),
  actorName: text("actor_name"),
  entityType: text("entity_type").notNull(),
  entityId: uuid("entity_id").notNull(),
  entityName: text("entity_name"),
  action: text("action").notNull(),
  field: text("field"),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// User views — saved filter/sort/group configurations
export const userViews = pgTable("user_views", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  name: text("name").notNull(),
  entityType: text("entity_type").notNull(),
  viewType: text("view_type").notNull().default("table"),
  config: jsonb("config")
    .$type<{
      filters?: Record<string, unknown>;
      sort?: Record<string, unknown>;
      groupBy?: string;
      columns?: string[];
    }>()
    .notNull(),
  isDefault: boolean("is_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// =============================================================================
// Phase 3 — Installation tables
// =============================================================================

// Installations — project-level grouping of kiosks with date range and status
export const installations = pgTable("installations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  region: text("region"),
  status: text("status").notNull().default("planned"),
  plannedStart: timestamp("planned_start", { withTimezone: true }),
  plannedEnd: timestamp("planned_end", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Milestones — key dates on an installation (contract signing, go-live, etc.)
export const milestones = pgTable("milestones", {
  id: uuid("id").primaryKey().defaultRandom(),
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  targetDate: timestamp("target_date", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// installationKiosks — join table linking installations to kiosks
export const installationKiosks = pgTable("installation_kiosks", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  kioskId: uuid("kiosk_id")
    .notNull()
    .references(() => kiosks.id, { onDelete: "cascade" }),
}, (t) => [primaryKey({ columns: [t.installationId, t.kioskId] })]);

// installationMembers — join table for team members on an installation
export const installationMembers = pgTable("installation_members", {
  installationId: uuid("installation_id")
    .notNull()
    .references(() => installations.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").notNull(),
}, (t) => [primaryKey({ columns: [t.installationId, t.userId] })]);

// =============================================================================
// Phase 4 — Product/Provider tables
// =============================================================================

// Products — distinct product types (e.g. Transfers, Tours & Activities)
export const products = pgTable("products", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Providers — companies providing products (e.g. Uber, TUI Musement)
export const providers = pgTable("providers", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Location products — per-hotel product availability, provider assignment, and commission tiers
export const locationProducts = pgTable("location_products", {
  id: uuid("id").primaryKey().defaultRandom(),
  locationId: uuid("location_id").notNull().references(() => locations.id),
  productId: uuid("product_id").notNull().references(() => products.id),
  providerId: uuid("provider_id").references(() => providers.id),
  availability: text("availability").notNull().default("unavailable"),
  commissionTiers: jsonb("commission_tiers").$type<Array<{ minRevenue: number; maxRevenue: number | null; rate: number }>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// Phase 4.1 note: appSettings already declared above (line ~88).

// Duplicate dismissals — admin marks a pair of locations as "not duplicates";
// stored canonical-ordered (locationAId < locationBId lexicographically) so
// the UNIQUE constraint collapses both directions of the pair.
export const duplicateDismissals = pgTable(
  "duplicate_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    locationAId: uuid("location_a_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    locationBId: uuid("location_b_id").notNull().references(() => locations.id, { onDelete: "cascade" }),
    dismissedBy: text("dismissed_by").notNull(),
    dismissedByName: text("dismissed_by_name").notNull(),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    uniqueIndex("duplicate_dismissals_pair_idx").on(t.locationAId, t.locationBId),
  ]
);

// =============================================================================
// Phase 1 — User scopes (dimension-based access scoping)
// =============================================================================

// INVARIANT: users with userType='external' MUST have >=1 row in userScopes.
// Enforced in invite-accept handler (src/lib/auth/invite.ts) and in scopedQuery().
// Not enforced at DB layer because insert-ordering makes a CHECK constraint impractical.
export const userScopes = pgTable(
  "user_scopes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    dimensionType: text("dimension_type", {
      enum: [
        "hotel_group",
        "location",
        "region",
        "product",
        "provider",
        "location_group",
      ],
    }).notNull(),
    dimensionId: text("dimension_id").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    createdBy: text("created_by").references(() => user.id),
  },
  (t) => ({
    uniq: unique().on(t.userId, t.dimensionType, t.dimensionId),
    byUser: index("user_scopes_user_idx").on(t.userId),
  })
);
